# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

apiUrl: Optional[str]
"""
The URL of the Border0 API. Can also be set with the `BORDER0_API` environment variable. Defaults to
`https://api.border0.com/api/v1`.
"""

httpClientTimeout: Optional[str]
"""
The timeout for each HTTP request. Can also be set with the `BORDER0_HTTP_CLIENT_TIMEOUT` environment variable. Defaults
to `30s`.
"""

token: Optional[str]
"""
The auth token used to authenticate with the Border0 API. Can also be set with the `BORDER0_TOKEN` environment variable.
If you need to generate a Border0 access token, go to [Border0 Admin Portal](https://portal.border0.com) > Organization
Settings > Access Tokens, create a token in `Member` permission groups.
"""

