[project]
name = "tailscale-demo"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "pulumi>=3.0.0,<4.0.0",
    "pulumi-aws>=7.0.0,<8.0.0",
    "pulumi-awsx>=3.6.0",
    "pulumi-cloudinit-tailscale",
    "pulumi-tailscale",
]

[tool.uv.sources]
pulumi-cloudinit-tailscale = { path = "projects/aws/vpn/sdks/cloudinit-tailscale" }
pulumi-tailscale = { path = "projects/aws/vpn/sdks/tailscale" }
