# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .connector import *
from .connector_token import *
from .get_group_names_to_ids import *
from .get_policy_document import *
from .get_policy_v2_document import *
from .get_user_emails_to_ids import *
from .group import *
from .policy import *
from .policy_attachment import *
from .provider import *
from .service_account import *
from .service_account_token import *
from .socket import *
from .user import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_border0.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_border0.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "border0",
  "mod": "index/connector",
  "fqn": "pulumi_border0",
  "classes": {
   "border0:index/connector:Connector": "Connector"
  }
 },
 {
  "pkg": "border0",
  "mod": "index/connectorToken",
  "fqn": "pulumi_border0",
  "classes": {
   "border0:index/connectorToken:ConnectorToken": "ConnectorToken"
  }
 },
 {
  "pkg": "border0",
  "mod": "index/group",
  "fqn": "pulumi_border0",
  "classes": {
   "border0:index/group:Group": "Group"
  }
 },
 {
  "pkg": "border0",
  "mod": "index/policy",
  "fqn": "pulumi_border0",
  "classes": {
   "border0:index/policy:Policy": "Policy"
  }
 },
 {
  "pkg": "border0",
  "mod": "index/policyAttachment",
  "fqn": "pulumi_border0",
  "classes": {
   "border0:index/policyAttachment:PolicyAttachment": "PolicyAttachment"
  }
 },
 {
  "pkg": "border0",
  "mod": "index/serviceAccount",
  "fqn": "pulumi_border0",
  "classes": {
   "border0:index/serviceAccount:ServiceAccount": "ServiceAccount"
  }
 },
 {
  "pkg": "border0",
  "mod": "index/serviceAccountToken",
  "fqn": "pulumi_border0",
  "classes": {
   "border0:index/serviceAccountToken:ServiceAccountToken": "ServiceAccountToken"
  }
 },
 {
  "pkg": "border0",
  "mod": "index/socket",
  "fqn": "pulumi_border0",
  "classes": {
   "border0:index/socket:Socket": "Socket"
  }
 },
 {
  "pkg": "border0",
  "mod": "index/user",
  "fqn": "pulumi_border0",
  "classes": {
   "border0:index/user:User": "User"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "border0",
  "token": "pulumi:providers:border0",
  "fqn": "pulumi_border0",
  "class": "Provider"
 }
]
"""
)
