# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ConnectorTokenArgs', 'ConnectorToken']

@pulumi.input_type
class ConnectorTokenArgs:
    def __init__(__self__, *,
                 connector_id: pulumi.Input[_builtins.str],
                 connector_token_id: Optional[pulumi.Input[_builtins.str]] = None,
                 expires_at: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a ConnectorToken resource.

        :param pulumi.Input[_builtins.str] connector_id: The ID of the connector.
        :param pulumi.Input[_builtins.str] expires_at: The expiration date and time of the token. Leave empty for no expiration.
        :param pulumi.Input[_builtins.str] name: The name of the connector token. Connector token name must contain only lowercase letters, numbers and dashes.
        """
        pulumi.set(__self__, "connector_id", connector_id)
        if connector_token_id is not None:
            pulumi.set(__self__, "connector_token_id", connector_token_id)
        if expires_at is not None:
            pulumi.set(__self__, "expires_at", expires_at)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="connectorId")
    def connector_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the connector.
        """
        return pulumi.get(self, "connector_id")

    @connector_id.setter
    def connector_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "connector_id", value)

    @_builtins.property
    @pulumi.getter(name="connectorTokenId")
    def connector_token_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "connector_token_id")

    @connector_token_id.setter
    def connector_token_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "connector_token_id", value)

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The expiration date and time of the token. Leave empty for no expiration.
        """
        return pulumi.get(self, "expires_at")

    @expires_at.setter
    def expires_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "expires_at", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the connector token. Connector token name must contain only lowercase letters, numbers and dashes.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _ConnectorTokenState:
    def __init__(__self__, *,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_token_id: Optional[pulumi.Input[_builtins.str]] = None,
                 expires_at: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 token: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ConnectorToken resources.

        :param pulumi.Input[_builtins.str] connector_id: The ID of the connector.
        :param pulumi.Input[_builtins.str] expires_at: The expiration date and time of the token. Leave empty for no expiration.
        :param pulumi.Input[_builtins.str] name: The name of the connector token. Connector token name must contain only lowercase letters, numbers and dashes.
        :param pulumi.Input[_builtins.str] token: The generated connector token.
        """
        if connector_id is not None:
            pulumi.set(__self__, "connector_id", connector_id)
        if connector_token_id is not None:
            pulumi.set(__self__, "connector_token_id", connector_token_id)
        if expires_at is not None:
            pulumi.set(__self__, "expires_at", expires_at)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter(name="connectorId")
    def connector_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the connector.
        """
        return pulumi.get(self, "connector_id")

    @connector_id.setter
    def connector_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "connector_id", value)

    @_builtins.property
    @pulumi.getter(name="connectorTokenId")
    def connector_token_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "connector_token_id")

    @connector_token_id.setter
    def connector_token_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "connector_token_id", value)

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The expiration date and time of the token. Leave empty for no expiration.
        """
        return pulumi.get(self, "expires_at")

    @expires_at.setter
    def expires_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "expires_at", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the connector token. Connector token name must contain only lowercase letters, numbers and dashes.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The generated connector token.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "token", value)


@pulumi.type_token("border0:index/connectorToken:ConnectorToken")
class ConnectorToken(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_token_id: Optional[pulumi.Input[_builtins.str]] = None,
                 expires_at: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a ConnectorToken resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] connector_id: The ID of the connector.
        :param pulumi.Input[_builtins.str] expires_at: The expiration date and time of the token. Leave empty for no expiration.
        :param pulumi.Input[_builtins.str] name: The name of the connector token. Connector token name must contain only lowercase letters, numbers and dashes.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ConnectorTokenArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ConnectorToken resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ConnectorTokenArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ConnectorTokenArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_token_id: Optional[pulumi.Input[_builtins.str]] = None,
                 expires_at: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ConnectorTokenArgs.__new__(ConnectorTokenArgs)

            if connector_id is None and not opts.urn:
                raise TypeError("Missing required property 'connector_id'")
            __props__.__dict__["connector_id"] = connector_id
            __props__.__dict__["connector_token_id"] = connector_token_id
            __props__.__dict__["expires_at"] = expires_at
            __props__.__dict__["name"] = name
            __props__.__dict__["token"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["token"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ConnectorToken, __self__).__init__(
            'border0:index/connectorToken:ConnectorToken',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            connector_id: Optional[pulumi.Input[_builtins.str]] = None,
            connector_token_id: Optional[pulumi.Input[_builtins.str]] = None,
            expires_at: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            token: Optional[pulumi.Input[_builtins.str]] = None) -> 'ConnectorToken':
        """
        Get an existing ConnectorToken resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] connector_id: The ID of the connector.
        :param pulumi.Input[_builtins.str] expires_at: The expiration date and time of the token. Leave empty for no expiration.
        :param pulumi.Input[_builtins.str] name: The name of the connector token. Connector token name must contain only lowercase letters, numbers and dashes.
        :param pulumi.Input[_builtins.str] token: The generated connector token.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ConnectorTokenState.__new__(_ConnectorTokenState)

        __props__.__dict__["connector_id"] = connector_id
        __props__.__dict__["connector_token_id"] = connector_token_id
        __props__.__dict__["expires_at"] = expires_at
        __props__.__dict__["name"] = name
        __props__.__dict__["token"] = token
        return ConnectorToken(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="connectorId")
    def connector_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the connector.
        """
        return pulumi.get(self, "connector_id")

    @_builtins.property
    @pulumi.getter(name="connectorTokenId")
    def connector_token_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "connector_token_id")

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The expiration date and time of the token. Leave empty for no expiration.
        """
        return pulumi.get(self, "expires_at")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the connector token. Connector token name must contain only lowercase letters, numbers and dashes.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def token(self) -> pulumi.Output[_builtins.str]:
        """
        The generated connector token.
        """
        return pulumi.get(self, "token")

