# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ConnectorArgs', 'Connector']

@pulumi.input_type
class ConnectorArgs:
    def __init__(__self__, *,
                 built_in_ssh_service_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Connector resource.

        :param pulumi.Input[_builtins.bool] built_in_ssh_service_enabled: Whether to expose the connector as an ssh service.
        :param pulumi.Input[_builtins.str] description: The description of the connector.
        :param pulumi.Input[_builtins.str] name: The name of the connector. Connector name must contain only lowercase letters, numbers and dashes.
        """
        if built_in_ssh_service_enabled is not None:
            pulumi.set(__self__, "built_in_ssh_service_enabled", built_in_ssh_service_enabled)
        if connector_id is not None:
            pulumi.set(__self__, "connector_id", connector_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="builtInSshServiceEnabled")
    def built_in_ssh_service_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether to expose the connector as an ssh service.
        """
        return pulumi.get(self, "built_in_ssh_service_enabled")

    @built_in_ssh_service_enabled.setter
    def built_in_ssh_service_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "built_in_ssh_service_enabled", value)

    @_builtins.property
    @pulumi.getter(name="connectorId")
    def connector_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "connector_id")

    @connector_id.setter
    def connector_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "connector_id", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The description of the connector.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the connector. Connector name must contain only lowercase letters, numbers and dashes.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _ConnectorState:
    def __init__(__self__, *,
                 built_in_ssh_service_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 built_in_ssh_service_id: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscale_auth_key: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Connector resources.

        :param pulumi.Input[_builtins.bool] built_in_ssh_service_enabled: Whether to expose the connector as an ssh service.
        :param pulumi.Input[_builtins.str] built_in_ssh_service_id: The socket id of the built-in ssh service.
        :param pulumi.Input[_builtins.str] description: The description of the connector.
        :param pulumi.Input[_builtins.str] name: The name of the connector. Connector name must contain only lowercase letters, numbers and dashes.
        :param pulumi.Input[_builtins.str] tailscale_auth_key: The Tailscale auth key for this connector. Only populated on create for Tailscale-managed organizations.
        """
        if built_in_ssh_service_enabled is not None:
            pulumi.set(__self__, "built_in_ssh_service_enabled", built_in_ssh_service_enabled)
        if built_in_ssh_service_id is not None:
            pulumi.set(__self__, "built_in_ssh_service_id", built_in_ssh_service_id)
        if connector_id is not None:
            pulumi.set(__self__, "connector_id", connector_id)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if tailscale_auth_key is not None:
            pulumi.set(__self__, "tailscale_auth_key", tailscale_auth_key)

    @_builtins.property
    @pulumi.getter(name="builtInSshServiceEnabled")
    def built_in_ssh_service_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether to expose the connector as an ssh service.
        """
        return pulumi.get(self, "built_in_ssh_service_enabled")

    @built_in_ssh_service_enabled.setter
    def built_in_ssh_service_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "built_in_ssh_service_enabled", value)

    @_builtins.property
    @pulumi.getter(name="builtInSshServiceId")
    def built_in_ssh_service_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The socket id of the built-in ssh service.
        """
        return pulumi.get(self, "built_in_ssh_service_id")

    @built_in_ssh_service_id.setter
    def built_in_ssh_service_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "built_in_ssh_service_id", value)

    @_builtins.property
    @pulumi.getter(name="connectorId")
    def connector_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "connector_id")

    @connector_id.setter
    def connector_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "connector_id", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The description of the connector.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the connector. Connector name must contain only lowercase letters, numbers and dashes.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="tailscaleAuthKey")
    def tailscale_auth_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The Tailscale auth key for this connector. Only populated on create for Tailscale-managed organizations.
        """
        return pulumi.get(self, "tailscale_auth_key")

    @tailscale_auth_key.setter
    def tailscale_auth_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tailscale_auth_key", value)


@pulumi.type_token("border0:index/connector:Connector")
class Connector(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 built_in_ssh_service_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Connector resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] built_in_ssh_service_enabled: Whether to expose the connector as an ssh service.
        :param pulumi.Input[_builtins.str] description: The description of the connector.
        :param pulumi.Input[_builtins.str] name: The name of the connector. Connector name must contain only lowercase letters, numbers and dashes.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ConnectorArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Connector resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ConnectorArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ConnectorArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 built_in_ssh_service_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ConnectorArgs.__new__(ConnectorArgs)

            __props__.__dict__["built_in_ssh_service_enabled"] = built_in_ssh_service_enabled
            __props__.__dict__["connector_id"] = connector_id
            __props__.__dict__["description"] = description
            __props__.__dict__["name"] = name
            __props__.__dict__["built_in_ssh_service_id"] = None
            __props__.__dict__["tailscale_auth_key"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["tailscaleAuthKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Connector, __self__).__init__(
            'border0:index/connector:Connector',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            built_in_ssh_service_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
            built_in_ssh_service_id: Optional[pulumi.Input[_builtins.str]] = None,
            connector_id: Optional[pulumi.Input[_builtins.str]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            tailscale_auth_key: Optional[pulumi.Input[_builtins.str]] = None) -> 'Connector':
        """
        Get an existing Connector resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] built_in_ssh_service_enabled: Whether to expose the connector as an ssh service.
        :param pulumi.Input[_builtins.str] built_in_ssh_service_id: The socket id of the built-in ssh service.
        :param pulumi.Input[_builtins.str] description: The description of the connector.
        :param pulumi.Input[_builtins.str] name: The name of the connector. Connector name must contain only lowercase letters, numbers and dashes.
        :param pulumi.Input[_builtins.str] tailscale_auth_key: The Tailscale auth key for this connector. Only populated on create for Tailscale-managed organizations.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ConnectorState.__new__(_ConnectorState)

        __props__.__dict__["built_in_ssh_service_enabled"] = built_in_ssh_service_enabled
        __props__.__dict__["built_in_ssh_service_id"] = built_in_ssh_service_id
        __props__.__dict__["connector_id"] = connector_id
        __props__.__dict__["description"] = description
        __props__.__dict__["name"] = name
        __props__.__dict__["tailscale_auth_key"] = tailscale_auth_key
        return Connector(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="builtInSshServiceEnabled")
    def built_in_ssh_service_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to expose the connector as an ssh service.
        """
        return pulumi.get(self, "built_in_ssh_service_enabled")

    @_builtins.property
    @pulumi.getter(name="builtInSshServiceId")
    def built_in_ssh_service_id(self) -> pulumi.Output[_builtins.str]:
        """
        The socket id of the built-in ssh service.
        """
        return pulumi.get(self, "built_in_ssh_service_id")

    @_builtins.property
    @pulumi.getter(name="connectorId")
    def connector_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "connector_id")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The description of the connector.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the connector. Connector name must contain only lowercase letters, numbers and dashes.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="tailscaleAuthKey")
    def tailscale_auth_key(self) -> pulumi.Output[_builtins.str]:
        """
        The Tailscale auth key for this connector. Only populated on create for Tailscale-managed organizations.
        """
        return pulumi.get(self, "tailscale_auth_key")

