# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetGroupNamesToIdsResult',
    'AwaitableGetGroupNamesToIdsResult',
    'get_group_names_to_ids',
    'get_group_names_to_ids_output',
]

@pulumi.output_type
class GetGroupNamesToIdsResult:
    """
    A collection of values returned by getGroupNamesToIds.
    """
    def __init__(__self__, id=None, ids=None, names=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if ids and not isinstance(ids, list):
            raise TypeError("Expected argument 'ids' to be a list")
        pulumi.set(__self__, "ids", ids)
        if names and not isinstance(names, list):
            raise TypeError("Expected argument 'names' to be a list")
        pulumi.set(__self__, "names", names)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def ids(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "ids")

    @_builtins.property
    @pulumi.getter
    def names(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "names")


class AwaitableGetGroupNamesToIdsResult(GetGroupNamesToIdsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetGroupNamesToIdsResult(
            id=self.id,
            ids=self.ids,
            names=self.names)


def get_group_names_to_ids(id: Optional[_builtins.str] = None,
                           names: Optional[Sequence[_builtins.str]] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetGroupNamesToIdsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['names'] = names
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('border0:index/getGroupNamesToIds:getGroupNamesToIds', __args__, opts=opts, typ=GetGroupNamesToIdsResult, package_ref=_utilities.get_package()).value

    return AwaitableGetGroupNamesToIdsResult(
        id=pulumi.get(__ret__, 'id'),
        ids=pulumi.get(__ret__, 'ids'),
        names=pulumi.get(__ret__, 'names'))
def get_group_names_to_ids_output(id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                  names: Optional[pulumi.Input[Sequence[_builtins.str]]] = None,
                                  opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetGroupNamesToIdsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['names'] = names
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('border0:index/getGroupNamesToIds:getGroupNamesToIds', __args__, opts=opts, typ=GetGroupNamesToIdsResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetGroupNamesToIdsResult(
        id=pulumi.get(__response__, 'id'),
        ids=pulumi.get(__response__, 'ids'),
        names=pulumi.get(__response__, 'names')))
