# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetUserEmailsToIdsResult',
    'AwaitableGetUserEmailsToIdsResult',
    'get_user_emails_to_ids',
    'get_user_emails_to_ids_output',
]

@pulumi.output_type
class GetUserEmailsToIdsResult:
    """
    A collection of values returned by getUserEmailsToIds.
    """
    def __init__(__self__, emails=None, id=None, ids=None):
        if emails and not isinstance(emails, list):
            raise TypeError("Expected argument 'emails' to be a list")
        pulumi.set(__self__, "emails", emails)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if ids and not isinstance(ids, list):
            raise TypeError("Expected argument 'ids' to be a list")
        pulumi.set(__self__, "ids", ids)

    @_builtins.property
    @pulumi.getter
    def emails(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "emails")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def ids(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "ids")


class AwaitableGetUserEmailsToIdsResult(GetUserEmailsToIdsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetUserEmailsToIdsResult(
            emails=self.emails,
            id=self.id,
            ids=self.ids)


def get_user_emails_to_ids(emails: Optional[Sequence[_builtins.str]] = None,
                           id: Optional[_builtins.str] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetUserEmailsToIdsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['emails'] = emails
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('border0:index/getUserEmailsToIds:getUserEmailsToIds', __args__, opts=opts, typ=GetUserEmailsToIdsResult, package_ref=_utilities.get_package()).value

    return AwaitableGetUserEmailsToIdsResult(
        emails=pulumi.get(__ret__, 'emails'),
        id=pulumi.get(__ret__, 'id'),
        ids=pulumi.get(__ret__, 'ids'))
def get_user_emails_to_ids_output(emails: Optional[pulumi.Input[Sequence[_builtins.str]]] = None,
                                  id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                  opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetUserEmailsToIdsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['emails'] = emails
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('border0:index/getUserEmailsToIds:getUserEmailsToIds', __args__, opts=opts, typ=GetUserEmailsToIdsResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetUserEmailsToIdsResult(
        emails=pulumi.get(__response__, 'emails'),
        id=pulumi.get(__response__, 'id'),
        ids=pulumi.get(__response__, 'ids')))
