# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetPolicyV2DocumentResult',
    'AwaitableGetPolicyV2DocumentResult',
    'get_policy_v2_document',
    'get_policy_v2_document_output',
]

@pulumi.output_type
class GetPolicyV2DocumentResult:
    """
    A collection of values returned by getPolicyV2Document.
    """
    def __init__(__self__, conditions=None, id=None, json=None, permissions=None):
        if conditions and not isinstance(conditions, list):
            raise TypeError("Expected argument 'conditions' to be a list")
        pulumi.set(__self__, "conditions", conditions)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if json and not isinstance(json, str):
            raise TypeError("Expected argument 'json' to be a str")
        pulumi.set(__self__, "json", json)
        if permissions and not isinstance(permissions, list):
            raise TypeError("Expected argument 'permissions' to be a list")
        pulumi.set(__self__, "permissions", permissions)

    @_builtins.property
    @pulumi.getter
    def conditions(self) -> Sequence['outputs.GetPolicyV2DocumentConditionResult']:
        return pulumi.get(self, "conditions")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def json(self) -> _builtins.str:
        return pulumi.get(self, "json")

    @_builtins.property
    @pulumi.getter
    def permissions(self) -> Sequence['outputs.GetPolicyV2DocumentPermissionResult']:
        return pulumi.get(self, "permissions")


class AwaitableGetPolicyV2DocumentResult(GetPolicyV2DocumentResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetPolicyV2DocumentResult(
            conditions=self.conditions,
            id=self.id,
            json=self.json,
            permissions=self.permissions)


def get_policy_v2_document(conditions: Optional[Sequence[Union['GetPolicyV2DocumentConditionArgs', 'GetPolicyV2DocumentConditionArgsDict']]] = None,
                           id: Optional[_builtins.str] = None,
                           permissions: Optional[Sequence[Union['GetPolicyV2DocumentPermissionArgs', 'GetPolicyV2DocumentPermissionArgsDict']]] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetPolicyV2DocumentResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['conditions'] = conditions
    __args__['id'] = id
    __args__['permissions'] = permissions
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('border0:index/getPolicyV2Document:getPolicyV2Document', __args__, opts=opts, typ=GetPolicyV2DocumentResult, package_ref=_utilities.get_package()).value

    return AwaitableGetPolicyV2DocumentResult(
        conditions=pulumi.get(__ret__, 'conditions'),
        id=pulumi.get(__ret__, 'id'),
        json=pulumi.get(__ret__, 'json'),
        permissions=pulumi.get(__ret__, 'permissions'))
def get_policy_v2_document_output(conditions: Optional[pulumi.Input[Sequence[Union['GetPolicyV2DocumentConditionArgs', 'GetPolicyV2DocumentConditionArgsDict']]]] = None,
                                  id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                  permissions: Optional[pulumi.Input[Sequence[Union['GetPolicyV2DocumentPermissionArgs', 'GetPolicyV2DocumentPermissionArgsDict']]]] = None,
                                  opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetPolicyV2DocumentResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['conditions'] = conditions
    __args__['id'] = id
    __args__['permissions'] = permissions
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('border0:index/getPolicyV2Document:getPolicyV2Document', __args__, opts=opts, typ=GetPolicyV2DocumentResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetPolicyV2DocumentResult(
        conditions=pulumi.get(__response__, 'conditions'),
        id=pulumi.get(__response__, 'id'),
        json=pulumi.get(__response__, 'json'),
        permissions=pulumi.get(__response__, 'permissions')))
