# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['PolicyAttachmentArgs', 'PolicyAttachment']

@pulumi.input_type
class PolicyAttachmentArgs:
    def __init__(__self__, *,
                 policy_id: pulumi.Input[_builtins.str],
                 socket_id: pulumi.Input[_builtins.str],
                 policy_attachment_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a PolicyAttachment resource.

        :param pulumi.Input[_builtins.str] policy_id: The ID of the policy to attach.
        :param pulumi.Input[_builtins.str] socket_id: The ID of the socket to attach the policy to.
        """
        pulumi.set(__self__, "policy_id", policy_id)
        pulumi.set(__self__, "socket_id", socket_id)
        if policy_attachment_id is not None:
            pulumi.set(__self__, "policy_attachment_id", policy_attachment_id)

    @_builtins.property
    @pulumi.getter(name="policyId")
    def policy_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the policy to attach.
        """
        return pulumi.get(self, "policy_id")

    @policy_id.setter
    def policy_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "policy_id", value)

    @_builtins.property
    @pulumi.getter(name="socketId")
    def socket_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the socket to attach the policy to.
        """
        return pulumi.get(self, "socket_id")

    @socket_id.setter
    def socket_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "socket_id", value)

    @_builtins.property
    @pulumi.getter(name="policyAttachmentId")
    def policy_attachment_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "policy_attachment_id")

    @policy_attachment_id.setter
    def policy_attachment_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "policy_attachment_id", value)


@pulumi.input_type
class _PolicyAttachmentState:
    def __init__(__self__, *,
                 policy_attachment_id: Optional[pulumi.Input[_builtins.str]] = None,
                 policy_id: Optional[pulumi.Input[_builtins.str]] = None,
                 socket_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering PolicyAttachment resources.

        :param pulumi.Input[_builtins.str] policy_id: The ID of the policy to attach.
        :param pulumi.Input[_builtins.str] socket_id: The ID of the socket to attach the policy to.
        """
        if policy_attachment_id is not None:
            pulumi.set(__self__, "policy_attachment_id", policy_attachment_id)
        if policy_id is not None:
            pulumi.set(__self__, "policy_id", policy_id)
        if socket_id is not None:
            pulumi.set(__self__, "socket_id", socket_id)

    @_builtins.property
    @pulumi.getter(name="policyAttachmentId")
    def policy_attachment_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "policy_attachment_id")

    @policy_attachment_id.setter
    def policy_attachment_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "policy_attachment_id", value)

    @_builtins.property
    @pulumi.getter(name="policyId")
    def policy_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the policy to attach.
        """
        return pulumi.get(self, "policy_id")

    @policy_id.setter
    def policy_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "policy_id", value)

    @_builtins.property
    @pulumi.getter(name="socketId")
    def socket_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the socket to attach the policy to.
        """
        return pulumi.get(self, "socket_id")

    @socket_id.setter
    def socket_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "socket_id", value)


@pulumi.type_token("border0:index/policyAttachment:PolicyAttachment")
class PolicyAttachment(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 policy_attachment_id: Optional[pulumi.Input[_builtins.str]] = None,
                 policy_id: Optional[pulumi.Input[_builtins.str]] = None,
                 socket_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a PolicyAttachment resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] policy_id: The ID of the policy to attach.
        :param pulumi.Input[_builtins.str] socket_id: The ID of the socket to attach the policy to.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: PolicyAttachmentArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a PolicyAttachment resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param PolicyAttachmentArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PolicyAttachmentArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 policy_attachment_id: Optional[pulumi.Input[_builtins.str]] = None,
                 policy_id: Optional[pulumi.Input[_builtins.str]] = None,
                 socket_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PolicyAttachmentArgs.__new__(PolicyAttachmentArgs)

            __props__.__dict__["policy_attachment_id"] = policy_attachment_id
            if policy_id is None and not opts.urn:
                raise TypeError("Missing required property 'policy_id'")
            __props__.__dict__["policy_id"] = policy_id
            if socket_id is None and not opts.urn:
                raise TypeError("Missing required property 'socket_id'")
            __props__.__dict__["socket_id"] = socket_id
        super(PolicyAttachment, __self__).__init__(
            'border0:index/policyAttachment:PolicyAttachment',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            policy_attachment_id: Optional[pulumi.Input[_builtins.str]] = None,
            policy_id: Optional[pulumi.Input[_builtins.str]] = None,
            socket_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'PolicyAttachment':
        """
        Get an existing PolicyAttachment resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] policy_id: The ID of the policy to attach.
        :param pulumi.Input[_builtins.str] socket_id: The ID of the socket to attach the policy to.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PolicyAttachmentState.__new__(_PolicyAttachmentState)

        __props__.__dict__["policy_attachment_id"] = policy_attachment_id
        __props__.__dict__["policy_id"] = policy_id
        __props__.__dict__["socket_id"] = socket_id
        return PolicyAttachment(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="policyAttachmentId")
    def policy_attachment_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "policy_attachment_id")

    @_builtins.property
    @pulumi.getter(name="policyId")
    def policy_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the policy to attach.
        """
        return pulumi.get(self, "policy_id")

    @_builtins.property
    @pulumi.getter(name="socketId")
    def socket_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the socket to attach the policy to.
        """
        return pulumi.get(self, "socket_id")

