# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['PolicyArgs', 'Policy']

@pulumi.input_type
class PolicyArgs:
    def __init__(__self__, *,
                 policy_data: pulumi.Input[_builtins.str],
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 org_wide: Optional[pulumi.Input[_builtins.bool]] = None,
                 policy_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tag_rules: Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Policy resource.

        :param pulumi.Input[_builtins.str] policy_data: The policy data. This is a JSON string.
        :param pulumi.Input[_builtins.str] description: The description of the policy.
        :param pulumi.Input[_builtins.str] name: The name of the policy. Policy name must contain only lowercase letters, numbers and dashes.
        :param pulumi.Input[_builtins.bool] org_wide: Whether the policy should be applied to all sockets in the organization.
        :param pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]] tag_rules: A list of tag rules to apply to the sockets that this policy is applied to.
        :param pulumi.Input[_builtins.str] version: The version of the policy. The default value is 'v2', the other valid value is 'v1'.
        """
        pulumi.set(__self__, "policy_data", policy_data)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if org_wide is not None:
            pulumi.set(__self__, "org_wide", org_wide)
        if policy_id is not None:
            pulumi.set(__self__, "policy_id", policy_id)
        if tag_rules is not None:
            pulumi.set(__self__, "tag_rules", tag_rules)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter(name="policyData")
    def policy_data(self) -> pulumi.Input[_builtins.str]:
        """
        The policy data. This is a JSON string.
        """
        return pulumi.get(self, "policy_data")

    @policy_data.setter
    def policy_data(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "policy_data", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The description of the policy.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the policy. Policy name must contain only lowercase letters, numbers and dashes.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="orgWide")
    def org_wide(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the policy should be applied to all sockets in the organization.
        """
        return pulumi.get(self, "org_wide")

    @org_wide.setter
    def org_wide(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "org_wide", value)

    @_builtins.property
    @pulumi.getter(name="policyId")
    def policy_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "policy_id")

    @policy_id.setter
    def policy_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "policy_id", value)

    @_builtins.property
    @pulumi.getter(name="tagRules")
    def tag_rules(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]]]:
        """
        A list of tag rules to apply to the sockets that this policy is applied to.
        """
        return pulumi.get(self, "tag_rules")

    @tag_rules.setter
    def tag_rules(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]]]):
        pulumi.set(self, "tag_rules", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The version of the policy. The default value is 'v2', the other valid value is 'v1'.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)


@pulumi.input_type
class _PolicyState:
    def __init__(__self__, *,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 org_wide: Optional[pulumi.Input[_builtins.bool]] = None,
                 policy_data: Optional[pulumi.Input[_builtins.str]] = None,
                 policy_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tag_rules: Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Policy resources.

        :param pulumi.Input[_builtins.str] description: The description of the policy.
        :param pulumi.Input[_builtins.str] name: The name of the policy. Policy name must contain only lowercase letters, numbers and dashes.
        :param pulumi.Input[_builtins.bool] org_wide: Whether the policy should be applied to all sockets in the organization.
        :param pulumi.Input[_builtins.str] policy_data: The policy data. This is a JSON string.
        :param pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]] tag_rules: A list of tag rules to apply to the sockets that this policy is applied to.
        :param pulumi.Input[_builtins.str] version: The version of the policy. The default value is 'v2', the other valid value is 'v1'.
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if org_wide is not None:
            pulumi.set(__self__, "org_wide", org_wide)
        if policy_data is not None:
            pulumi.set(__self__, "policy_data", policy_data)
        if policy_id is not None:
            pulumi.set(__self__, "policy_id", policy_id)
        if tag_rules is not None:
            pulumi.set(__self__, "tag_rules", tag_rules)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The description of the policy.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the policy. Policy name must contain only lowercase letters, numbers and dashes.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="orgWide")
    def org_wide(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the policy should be applied to all sockets in the organization.
        """
        return pulumi.get(self, "org_wide")

    @org_wide.setter
    def org_wide(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "org_wide", value)

    @_builtins.property
    @pulumi.getter(name="policyData")
    def policy_data(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The policy data. This is a JSON string.
        """
        return pulumi.get(self, "policy_data")

    @policy_data.setter
    def policy_data(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "policy_data", value)

    @_builtins.property
    @pulumi.getter(name="policyId")
    def policy_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "policy_id")

    @policy_id.setter
    def policy_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "policy_id", value)

    @_builtins.property
    @pulumi.getter(name="tagRules")
    def tag_rules(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]]]:
        """
        A list of tag rules to apply to the sockets that this policy is applied to.
        """
        return pulumi.get(self, "tag_rules")

    @tag_rules.setter
    def tag_rules(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]]]):
        pulumi.set(self, "tag_rules", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The version of the policy. The default value is 'v2', the other valid value is 'v1'.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)


@pulumi.type_token("border0:index/policy:Policy")
class Policy(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 org_wide: Optional[pulumi.Input[_builtins.bool]] = None,
                 policy_data: Optional[pulumi.Input[_builtins.str]] = None,
                 policy_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tag_rules: Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Policy resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: The description of the policy.
        :param pulumi.Input[_builtins.str] name: The name of the policy. Policy name must contain only lowercase letters, numbers and dashes.
        :param pulumi.Input[_builtins.bool] org_wide: Whether the policy should be applied to all sockets in the organization.
        :param pulumi.Input[_builtins.str] policy_data: The policy data. This is a JSON string.
        :param pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]] tag_rules: A list of tag rules to apply to the sockets that this policy is applied to.
        :param pulumi.Input[_builtins.str] version: The version of the policy. The default value is 'v2', the other valid value is 'v1'.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: PolicyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Policy resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param PolicyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PolicyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 org_wide: Optional[pulumi.Input[_builtins.bool]] = None,
                 policy_data: Optional[pulumi.Input[_builtins.str]] = None,
                 policy_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tag_rules: Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]]] = None,
                 version: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PolicyArgs.__new__(PolicyArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["name"] = name
            __props__.__dict__["org_wide"] = org_wide
            if policy_data is None and not opts.urn:
                raise TypeError("Missing required property 'policy_data'")
            __props__.__dict__["policy_data"] = policy_data
            __props__.__dict__["policy_id"] = policy_id
            __props__.__dict__["tag_rules"] = tag_rules
            __props__.__dict__["version"] = version
        super(Policy, __self__).__init__(
            'border0:index/policy:Policy',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            org_wide: Optional[pulumi.Input[_builtins.bool]] = None,
            policy_data: Optional[pulumi.Input[_builtins.str]] = None,
            policy_id: Optional[pulumi.Input[_builtins.str]] = None,
            tag_rules: Optional[pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]]] = None,
            version: Optional[pulumi.Input[_builtins.str]] = None) -> 'Policy':
        """
        Get an existing Policy resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: The description of the policy.
        :param pulumi.Input[_builtins.str] name: The name of the policy. Policy name must contain only lowercase letters, numbers and dashes.
        :param pulumi.Input[_builtins.bool] org_wide: Whether the policy should be applied to all sockets in the organization.
        :param pulumi.Input[_builtins.str] policy_data: The policy data. This is a JSON string.
        :param pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]] tag_rules: A list of tag rules to apply to the sockets that this policy is applied to.
        :param pulumi.Input[_builtins.str] version: The version of the policy. The default value is 'v2', the other valid value is 'v1'.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PolicyState.__new__(_PolicyState)

        __props__.__dict__["description"] = description
        __props__.__dict__["name"] = name
        __props__.__dict__["org_wide"] = org_wide
        __props__.__dict__["policy_data"] = policy_data
        __props__.__dict__["policy_id"] = policy_id
        __props__.__dict__["tag_rules"] = tag_rules
        __props__.__dict__["version"] = version
        return Policy(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The description of the policy.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the policy. Policy name must contain only lowercase letters, numbers and dashes.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="orgWide")
    def org_wide(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the policy should be applied to all sockets in the organization.
        """
        return pulumi.get(self, "org_wide")

    @_builtins.property
    @pulumi.getter(name="policyData")
    def policy_data(self) -> pulumi.Output[_builtins.str]:
        """
        The policy data. This is a JSON string.
        """
        return pulumi.get(self, "policy_data")

    @_builtins.property
    @pulumi.getter(name="policyId")
    def policy_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "policy_id")

    @_builtins.property
    @pulumi.getter(name="tagRules")
    def tag_rules(self) -> pulumi.Output[Optional[Sequence[Mapping[str, _builtins.str]]]]:
        """
        A list of tag rules to apply to the sockets that this policy is applied to.
        """
        return pulumi.get(self, "tag_rules")

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The version of the policy. The default value is 'v2', the other valid value is 'v1'.
        """
        return pulumi.get(self, "version")

