# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProviderArgs', 'Provider']

@pulumi.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 api_url: Optional[pulumi.Input[_builtins.str]] = None,
                 http_client_timeout: Optional[pulumi.Input[_builtins.str]] = None,
                 token: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Provider resource.

        :param pulumi.Input[_builtins.str] api_url: The URL of the Border0 API. Can also be set with the `BORDER0_API` environment variable. Defaults to
               `https://api.border0.com/api/v1`.
        :param pulumi.Input[_builtins.str] http_client_timeout: The timeout for each HTTP request. Can also be set with the `BORDER0_HTTP_CLIENT_TIMEOUT` environment variable. Defaults
               to `30s`.
        :param pulumi.Input[_builtins.str] token: The auth token used to authenticate with the Border0 API. Can also be set with the `BORDER0_TOKEN` environment variable.
               If you need to generate a Border0 access token, go to [Border0 Admin Portal](https://portal.border0.com) > Organization
               Settings > Access Tokens, create a token in `Member` permission groups.
        """
        if api_url is not None:
            pulumi.set(__self__, "api_url", api_url)
        if http_client_timeout is not None:
            pulumi.set(__self__, "http_client_timeout", http_client_timeout)
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter(name="apiUrl")
    def api_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The URL of the Border0 API. Can also be set with the `BORDER0_API` environment variable. Defaults to
        `https://api.border0.com/api/v1`.
        """
        return pulumi.get(self, "api_url")

    @api_url.setter
    def api_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_url", value)

    @_builtins.property
    @pulumi.getter(name="httpClientTimeout")
    def http_client_timeout(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The timeout for each HTTP request. Can also be set with the `BORDER0_HTTP_CLIENT_TIMEOUT` environment variable. Defaults
        to `30s`.
        """
        return pulumi.get(self, "http_client_timeout")

    @http_client_timeout.setter
    def http_client_timeout(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "http_client_timeout", value)

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The auth token used to authenticate with the Border0 API. Can also be set with the `BORDER0_TOKEN` environment variable.
        If you need to generate a Border0 access token, go to [Border0 Admin Portal](https://portal.border0.com) > Organization
        Settings > Access Tokens, create a token in `Member` permission groups.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "token", value)


@pulumi.type_token("pulumi:providers:border0")
class Provider(pulumi.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_url: Optional[pulumi.Input[_builtins.str]] = None,
                 http_client_timeout: Optional[pulumi.Input[_builtins.str]] = None,
                 token: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        The provider type for the border0 package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] api_url: The URL of the Border0 API. Can also be set with the `BORDER0_API` environment variable. Defaults to
               `https://api.border0.com/api/v1`.
        :param pulumi.Input[_builtins.str] http_client_timeout: The timeout for each HTTP request. Can also be set with the `BORDER0_HTTP_CLIENT_TIMEOUT` environment variable. Defaults
               to `30s`.
        :param pulumi.Input[_builtins.str] token: The auth token used to authenticate with the Border0 API. Can also be set with the `BORDER0_TOKEN` environment variable.
               If you need to generate a Border0 access token, go to [Border0 Admin Portal](https://portal.border0.com) > Organization
               Settings > Access Tokens, create a token in `Member` permission groups.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ProviderArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The provider type for the border0 package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.


        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_url: Optional[pulumi.Input[_builtins.str]] = None,
                 http_client_timeout: Optional[pulumi.Input[_builtins.str]] = None,
                 token: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            __props__.__dict__["api_url"] = api_url
            __props__.__dict__["http_client_timeout"] = http_client_timeout
            __props__.__dict__["token"] = None if token is None else pulumi.Output.secret(token)
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["token"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Provider, __self__).__init__(
            'border0',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @_builtins.property
    @pulumi.getter(name="apiUrl")
    def api_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The URL of the Border0 API. Can also be set with the `BORDER0_API` environment variable. Defaults to
        `https://api.border0.com/api/v1`.
        """
        return pulumi.get(self, "api_url")

    @_builtins.property
    @pulumi.getter(name="httpClientTimeout")
    def http_client_timeout(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The timeout for each HTTP request. Can also be set with the `BORDER0_HTTP_CLIENT_TIMEOUT` environment variable. Defaults
        to `30s`.
        """
        return pulumi.get(self, "http_client_timeout")

    @_builtins.property
    @pulumi.getter
    def token(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The auth token used to authenticate with the Border0 API. Can also be set with the `BORDER0_TOKEN` environment variable.
        If you need to generate a Border0 access token, go to [Border0 Admin Portal](https://portal.border0.com) > Organization
        Settings > Access Tokens, create a token in `Member` permission groups.
        """
        return pulumi.get(self, "token")

