# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ServiceAccountTokenArgs', 'ServiceAccountToken']

@pulumi.input_type
class ServiceAccountTokenArgs:
    def __init__(__self__, *,
                 service_account_name: pulumi.Input[_builtins.str],
                 expires_at: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_token_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a ServiceAccountToken resource.

        :param pulumi.Input[_builtins.str] service_account_name: The name of the service account.
        :param pulumi.Input[_builtins.str] expires_at: The expiration date and time of the token. Leave empty for no expiration.
        :param pulumi.Input[_builtins.str] name: The name of the service account token. Service account token name must contain only lowercase letters, numbers and
               dashes.
        """
        pulumi.set(__self__, "service_account_name", service_account_name)
        if expires_at is not None:
            pulumi.set(__self__, "expires_at", expires_at)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if service_account_token_id is not None:
            pulumi.set(__self__, "service_account_token_id", service_account_token_id)

    @_builtins.property
    @pulumi.getter(name="serviceAccountName")
    def service_account_name(self) -> pulumi.Input[_builtins.str]:
        """
        The name of the service account.
        """
        return pulumi.get(self, "service_account_name")

    @service_account_name.setter
    def service_account_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "service_account_name", value)

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The expiration date and time of the token. Leave empty for no expiration.
        """
        return pulumi.get(self, "expires_at")

    @expires_at.setter
    def expires_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "expires_at", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the service account token. Service account token name must contain only lowercase letters, numbers and
        dashes.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="serviceAccountTokenId")
    def service_account_token_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "service_account_token_id")

    @service_account_token_id.setter
    def service_account_token_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "service_account_token_id", value)


@pulumi.input_type
class _ServiceAccountTokenState:
    def __init__(__self__, *,
                 expires_at: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_name: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_token_id: Optional[pulumi.Input[_builtins.str]] = None,
                 token: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ServiceAccountToken resources.

        :param pulumi.Input[_builtins.str] expires_at: The expiration date and time of the token. Leave empty for no expiration.
        :param pulumi.Input[_builtins.str] name: The name of the service account token. Service account token name must contain only lowercase letters, numbers and
               dashes.
        :param pulumi.Input[_builtins.str] service_account_name: The name of the service account.
        :param pulumi.Input[_builtins.str] token: The generated service account token.
        """
        if expires_at is not None:
            pulumi.set(__self__, "expires_at", expires_at)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if service_account_name is not None:
            pulumi.set(__self__, "service_account_name", service_account_name)
        if service_account_token_id is not None:
            pulumi.set(__self__, "service_account_token_id", service_account_token_id)
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The expiration date and time of the token. Leave empty for no expiration.
        """
        return pulumi.get(self, "expires_at")

    @expires_at.setter
    def expires_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "expires_at", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the service account token. Service account token name must contain only lowercase letters, numbers and
        dashes.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="serviceAccountName")
    def service_account_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the service account.
        """
        return pulumi.get(self, "service_account_name")

    @service_account_name.setter
    def service_account_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "service_account_name", value)

    @_builtins.property
    @pulumi.getter(name="serviceAccountTokenId")
    def service_account_token_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "service_account_token_id")

    @service_account_token_id.setter
    def service_account_token_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "service_account_token_id", value)

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The generated service account token.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "token", value)


@pulumi.type_token("border0:index/serviceAccountToken:ServiceAccountToken")
class ServiceAccountToken(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 expires_at: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_name: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_token_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a ServiceAccountToken resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] expires_at: The expiration date and time of the token. Leave empty for no expiration.
        :param pulumi.Input[_builtins.str] name: The name of the service account token. Service account token name must contain only lowercase letters, numbers and
               dashes.
        :param pulumi.Input[_builtins.str] service_account_name: The name of the service account.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ServiceAccountTokenArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ServiceAccountToken resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ServiceAccountTokenArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ServiceAccountTokenArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 expires_at: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_name: Optional[pulumi.Input[_builtins.str]] = None,
                 service_account_token_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ServiceAccountTokenArgs.__new__(ServiceAccountTokenArgs)

            __props__.__dict__["expires_at"] = expires_at
            __props__.__dict__["name"] = name
            if service_account_name is None and not opts.urn:
                raise TypeError("Missing required property 'service_account_name'")
            __props__.__dict__["service_account_name"] = service_account_name
            __props__.__dict__["service_account_token_id"] = service_account_token_id
            __props__.__dict__["token"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["token"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ServiceAccountToken, __self__).__init__(
            'border0:index/serviceAccountToken:ServiceAccountToken',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            expires_at: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            service_account_name: Optional[pulumi.Input[_builtins.str]] = None,
            service_account_token_id: Optional[pulumi.Input[_builtins.str]] = None,
            token: Optional[pulumi.Input[_builtins.str]] = None) -> 'ServiceAccountToken':
        """
        Get an existing ServiceAccountToken resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] expires_at: The expiration date and time of the token. Leave empty for no expiration.
        :param pulumi.Input[_builtins.str] name: The name of the service account token. Service account token name must contain only lowercase letters, numbers and
               dashes.
        :param pulumi.Input[_builtins.str] service_account_name: The name of the service account.
        :param pulumi.Input[_builtins.str] token: The generated service account token.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ServiceAccountTokenState.__new__(_ServiceAccountTokenState)

        __props__.__dict__["expires_at"] = expires_at
        __props__.__dict__["name"] = name
        __props__.__dict__["service_account_name"] = service_account_name
        __props__.__dict__["service_account_token_id"] = service_account_token_id
        __props__.__dict__["token"] = token
        return ServiceAccountToken(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The expiration date and time of the token. Leave empty for no expiration.
        """
        return pulumi.get(self, "expires_at")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the service account token. Service account token name must contain only lowercase letters, numbers and
        dashes.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="serviceAccountName")
    def service_account_name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the service account.
        """
        return pulumi.get(self, "service_account_name")

    @_builtins.property
    @pulumi.getter(name="serviceAccountTokenId")
    def service_account_token_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "service_account_token_id")

    @_builtins.property
    @pulumi.getter
    def token(self) -> pulumi.Output[_builtins.str]:
        """
        The generated service account token.
        """
        return pulumi.get(self, "token")

