# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['SocketArgs', 'Socket']

@pulumi.input_type
class SocketArgs:
    def __init__(__self__, *,
                 socket_type: pulumi.Input[_builtins.str],
                 aws_s3_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketAwsS3ConfigurationArgs']]]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 database_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketDatabaseConfigurationArgs']]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 elasticsearch_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketElasticsearchConfigurationArgs']]]] = None,
                 exit_node_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketExitNodeConfigurationArgs']]]] = None,
                 http_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketHttpConfigurationArgs']]]] = None,
                 kubernetes_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketKubernetesConfigurationArgs']]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 rdp_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketRdpConfigurationArgs']]]] = None,
                 recording_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 snowflake_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketSnowflakeConfigurationArgs']]]] = None,
                 socket_id: Optional[pulumi.Input[_builtins.str]] = None,
                 ssh_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketSshConfigurationArgs']]]] = None,
                 subnet_router_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketSubnetRouterConfigurationArgs']]]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tls_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketTlsConfigurationArgs']]]] = None,
                 upstream_type: Optional[pulumi.Input[_builtins.str]] = None,
                 vnc_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketVncConfigurationArgs']]]] = None):
        """
        The set of arguments for constructing a Socket resource.

        :param pulumi.Input[_builtins.str] socket_type: The type of the socket. Valid values: `ssh`, `http`, `database`, `tls`, `vnc`, `rdp`, `subnet_router`, `exit_node`,
               `snowflake`, `elasticsearch`, `kubernetes`, `aws_s3`.
        :param pulumi.Input[_builtins.str] connector_id: The ID of the connector that the socket is attached to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] connector_ids: The ID(s) of the connector(s) that the socket is attached to.
        :param pulumi.Input[_builtins.str] description: The description of the socket.
        :param pulumi.Input[_builtins.str] display_name: An additional display name of the socket. Less restrictive than the `name` field and does not need to be unique.
        :param pulumi.Input[_builtins.str] name: The name of the socket. Must be unique within your Border0 organization. Socket name can have alphanumerics and hyphens,
               but it must start or end with alphanumeric.
        :param pulumi.Input[_builtins.bool] recording_enabled: Indicates if session recording is enabled for the socket.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: The tags of the socket.
        :param pulumi.Input[_builtins.str] upstream_type: The upstream type of the socket.
        """
        pulumi.set(__self__, "socket_type", socket_type)
        if aws_s3_configurations is not None:
            pulumi.set(__self__, "aws_s3_configurations", aws_s3_configurations)
        if connector_id is not None:
            warnings.warn("""Deprecated""", DeprecationWarning)
            pulumi.log.warn("""connector_id is deprecated: Deprecated""")
        if connector_id is not None:
            pulumi.set(__self__, "connector_id", connector_id)
        if connector_ids is not None:
            pulumi.set(__self__, "connector_ids", connector_ids)
        if database_configurations is not None:
            pulumi.set(__self__, "database_configurations", database_configurations)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if elasticsearch_configurations is not None:
            pulumi.set(__self__, "elasticsearch_configurations", elasticsearch_configurations)
        if exit_node_configurations is not None:
            pulumi.set(__self__, "exit_node_configurations", exit_node_configurations)
        if http_configurations is not None:
            pulumi.set(__self__, "http_configurations", http_configurations)
        if kubernetes_configurations is not None:
            pulumi.set(__self__, "kubernetes_configurations", kubernetes_configurations)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if rdp_configurations is not None:
            pulumi.set(__self__, "rdp_configurations", rdp_configurations)
        if recording_enabled is not None:
            pulumi.set(__self__, "recording_enabled", recording_enabled)
        if snowflake_configurations is not None:
            pulumi.set(__self__, "snowflake_configurations", snowflake_configurations)
        if socket_id is not None:
            pulumi.set(__self__, "socket_id", socket_id)
        if ssh_configurations is not None:
            pulumi.set(__self__, "ssh_configurations", ssh_configurations)
        if subnet_router_configurations is not None:
            pulumi.set(__self__, "subnet_router_configurations", subnet_router_configurations)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tls_configurations is not None:
            pulumi.set(__self__, "tls_configurations", tls_configurations)
        if upstream_type is not None:
            pulumi.set(__self__, "upstream_type", upstream_type)
        if vnc_configurations is not None:
            pulumi.set(__self__, "vnc_configurations", vnc_configurations)

    @_builtins.property
    @pulumi.getter(name="socketType")
    def socket_type(self) -> pulumi.Input[_builtins.str]:
        """
        The type of the socket. Valid values: `ssh`, `http`, `database`, `tls`, `vnc`, `rdp`, `subnet_router`, `exit_node`,
        `snowflake`, `elasticsearch`, `kubernetes`, `aws_s3`.
        """
        return pulumi.get(self, "socket_type")

    @socket_type.setter
    def socket_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "socket_type", value)

    @_builtins.property
    @pulumi.getter(name="awsS3Configurations")
    def aws_s3_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketAwsS3ConfigurationArgs']]]]:
        return pulumi.get(self, "aws_s3_configurations")

    @aws_s3_configurations.setter
    def aws_s3_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketAwsS3ConfigurationArgs']]]]):
        pulumi.set(self, "aws_s3_configurations", value)

    @_builtins.property
    @pulumi.getter(name="connectorId")
    @_utilities.deprecated("""Deprecated""")
    def connector_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the connector that the socket is attached to.
        """
        return pulumi.get(self, "connector_id")

    @connector_id.setter
    def connector_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "connector_id", value)

    @_builtins.property
    @pulumi.getter(name="connectorIds")
    def connector_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The ID(s) of the connector(s) that the socket is attached to.
        """
        return pulumi.get(self, "connector_ids")

    @connector_ids.setter
    def connector_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "connector_ids", value)

    @_builtins.property
    @pulumi.getter(name="databaseConfigurations")
    def database_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketDatabaseConfigurationArgs']]]]:
        return pulumi.get(self, "database_configurations")

    @database_configurations.setter
    def database_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketDatabaseConfigurationArgs']]]]):
        pulumi.set(self, "database_configurations", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The description of the socket.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        An additional display name of the socket. Less restrictive than the `name` field and does not need to be unique.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter(name="elasticsearchConfigurations")
    def elasticsearch_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketElasticsearchConfigurationArgs']]]]:
        return pulumi.get(self, "elasticsearch_configurations")

    @elasticsearch_configurations.setter
    def elasticsearch_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketElasticsearchConfigurationArgs']]]]):
        pulumi.set(self, "elasticsearch_configurations", value)

    @_builtins.property
    @pulumi.getter(name="exitNodeConfigurations")
    def exit_node_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketExitNodeConfigurationArgs']]]]:
        return pulumi.get(self, "exit_node_configurations")

    @exit_node_configurations.setter
    def exit_node_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketExitNodeConfigurationArgs']]]]):
        pulumi.set(self, "exit_node_configurations", value)

    @_builtins.property
    @pulumi.getter(name="httpConfigurations")
    def http_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketHttpConfigurationArgs']]]]:
        return pulumi.get(self, "http_configurations")

    @http_configurations.setter
    def http_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketHttpConfigurationArgs']]]]):
        pulumi.set(self, "http_configurations", value)

    @_builtins.property
    @pulumi.getter(name="kubernetesConfigurations")
    def kubernetes_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketKubernetesConfigurationArgs']]]]:
        return pulumi.get(self, "kubernetes_configurations")

    @kubernetes_configurations.setter
    def kubernetes_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketKubernetesConfigurationArgs']]]]):
        pulumi.set(self, "kubernetes_configurations", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the socket. Must be unique within your Border0 organization. Socket name can have alphanumerics and hyphens,
        but it must start or end with alphanumeric.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="rdpConfigurations")
    def rdp_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketRdpConfigurationArgs']]]]:
        return pulumi.get(self, "rdp_configurations")

    @rdp_configurations.setter
    def rdp_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketRdpConfigurationArgs']]]]):
        pulumi.set(self, "rdp_configurations", value)

    @_builtins.property
    @pulumi.getter(name="recordingEnabled")
    def recording_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Indicates if session recording is enabled for the socket.
        """
        return pulumi.get(self, "recording_enabled")

    @recording_enabled.setter
    def recording_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "recording_enabled", value)

    @_builtins.property
    @pulumi.getter(name="snowflakeConfigurations")
    def snowflake_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketSnowflakeConfigurationArgs']]]]:
        return pulumi.get(self, "snowflake_configurations")

    @snowflake_configurations.setter
    def snowflake_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketSnowflakeConfigurationArgs']]]]):
        pulumi.set(self, "snowflake_configurations", value)

    @_builtins.property
    @pulumi.getter(name="socketId")
    def socket_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "socket_id")

    @socket_id.setter
    def socket_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "socket_id", value)

    @_builtins.property
    @pulumi.getter(name="sshConfigurations")
    def ssh_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketSshConfigurationArgs']]]]:
        return pulumi.get(self, "ssh_configurations")

    @ssh_configurations.setter
    def ssh_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketSshConfigurationArgs']]]]):
        pulumi.set(self, "ssh_configurations", value)

    @_builtins.property
    @pulumi.getter(name="subnetRouterConfigurations")
    def subnet_router_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketSubnetRouterConfigurationArgs']]]]:
        return pulumi.get(self, "subnet_router_configurations")

    @subnet_router_configurations.setter
    def subnet_router_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketSubnetRouterConfigurationArgs']]]]):
        pulumi.set(self, "subnet_router_configurations", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        The tags of the socket.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tlsConfigurations")
    def tls_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketTlsConfigurationArgs']]]]:
        return pulumi.get(self, "tls_configurations")

    @tls_configurations.setter
    def tls_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketTlsConfigurationArgs']]]]):
        pulumi.set(self, "tls_configurations", value)

    @_builtins.property
    @pulumi.getter(name="upstreamType")
    def upstream_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The upstream type of the socket.
        """
        return pulumi.get(self, "upstream_type")

    @upstream_type.setter
    def upstream_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "upstream_type", value)

    @_builtins.property
    @pulumi.getter(name="vncConfigurations")
    def vnc_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketVncConfigurationArgs']]]]:
        return pulumi.get(self, "vnc_configurations")

    @vnc_configurations.setter
    def vnc_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketVncConfigurationArgs']]]]):
        pulumi.set(self, "vnc_configurations", value)


@pulumi.input_type
class _SocketState:
    def __init__(__self__, *,
                 aws_s3_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketAwsS3ConfigurationArgs']]]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 database_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketDatabaseConfigurationArgs']]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 elasticsearch_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketElasticsearchConfigurationArgs']]]] = None,
                 exit_node_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketExitNodeConfigurationArgs']]]] = None,
                 http_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketHttpConfigurationArgs']]]] = None,
                 kubernetes_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketKubernetesConfigurationArgs']]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 rdp_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketRdpConfigurationArgs']]]] = None,
                 recording_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 snowflake_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketSnowflakeConfigurationArgs']]]] = None,
                 socket_id: Optional[pulumi.Input[_builtins.str]] = None,
                 socket_type: Optional[pulumi.Input[_builtins.str]] = None,
                 ssh_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketSshConfigurationArgs']]]] = None,
                 subnet_router_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketSubnetRouterConfigurationArgs']]]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tls_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketTlsConfigurationArgs']]]] = None,
                 upstream_type: Optional[pulumi.Input[_builtins.str]] = None,
                 vnc_configurations: Optional[pulumi.Input[Sequence[pulumi.Input['SocketVncConfigurationArgs']]]] = None):
        """
        Input properties used for looking up and filtering Socket resources.

        :param pulumi.Input[_builtins.str] connector_id: The ID of the connector that the socket is attached to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] connector_ids: The ID(s) of the connector(s) that the socket is attached to.
        :param pulumi.Input[_builtins.str] description: The description of the socket.
        :param pulumi.Input[_builtins.str] display_name: An additional display name of the socket. Less restrictive than the `name` field and does not need to be unique.
        :param pulumi.Input[_builtins.str] name: The name of the socket. Must be unique within your Border0 organization. Socket name can have alphanumerics and hyphens,
               but it must start or end with alphanumeric.
        :param pulumi.Input[_builtins.bool] recording_enabled: Indicates if session recording is enabled for the socket.
        :param pulumi.Input[_builtins.str] socket_type: The type of the socket. Valid values: `ssh`, `http`, `database`, `tls`, `vnc`, `rdp`, `subnet_router`, `exit_node`,
               `snowflake`, `elasticsearch`, `kubernetes`, `aws_s3`.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: The tags of the socket.
        :param pulumi.Input[_builtins.str] upstream_type: The upstream type of the socket.
        """
        if aws_s3_configurations is not None:
            pulumi.set(__self__, "aws_s3_configurations", aws_s3_configurations)
        if connector_id is not None:
            warnings.warn("""Deprecated""", DeprecationWarning)
            pulumi.log.warn("""connector_id is deprecated: Deprecated""")
        if connector_id is not None:
            pulumi.set(__self__, "connector_id", connector_id)
        if connector_ids is not None:
            pulumi.set(__self__, "connector_ids", connector_ids)
        if database_configurations is not None:
            pulumi.set(__self__, "database_configurations", database_configurations)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if elasticsearch_configurations is not None:
            pulumi.set(__self__, "elasticsearch_configurations", elasticsearch_configurations)
        if exit_node_configurations is not None:
            pulumi.set(__self__, "exit_node_configurations", exit_node_configurations)
        if http_configurations is not None:
            pulumi.set(__self__, "http_configurations", http_configurations)
        if kubernetes_configurations is not None:
            pulumi.set(__self__, "kubernetes_configurations", kubernetes_configurations)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if rdp_configurations is not None:
            pulumi.set(__self__, "rdp_configurations", rdp_configurations)
        if recording_enabled is not None:
            pulumi.set(__self__, "recording_enabled", recording_enabled)
        if snowflake_configurations is not None:
            pulumi.set(__self__, "snowflake_configurations", snowflake_configurations)
        if socket_id is not None:
            pulumi.set(__self__, "socket_id", socket_id)
        if socket_type is not None:
            pulumi.set(__self__, "socket_type", socket_type)
        if ssh_configurations is not None:
            pulumi.set(__self__, "ssh_configurations", ssh_configurations)
        if subnet_router_configurations is not None:
            pulumi.set(__self__, "subnet_router_configurations", subnet_router_configurations)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tls_configurations is not None:
            pulumi.set(__self__, "tls_configurations", tls_configurations)
        if upstream_type is not None:
            pulumi.set(__self__, "upstream_type", upstream_type)
        if vnc_configurations is not None:
            pulumi.set(__self__, "vnc_configurations", vnc_configurations)

    @_builtins.property
    @pulumi.getter(name="awsS3Configurations")
    def aws_s3_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketAwsS3ConfigurationArgs']]]]:
        return pulumi.get(self, "aws_s3_configurations")

    @aws_s3_configurations.setter
    def aws_s3_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketAwsS3ConfigurationArgs']]]]):
        pulumi.set(self, "aws_s3_configurations", value)

    @_builtins.property
    @pulumi.getter(name="connectorId")
    @_utilities.deprecated("""Deprecated""")
    def connector_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the connector that the socket is attached to.
        """
        return pulumi.get(self, "connector_id")

    @connector_id.setter
    def connector_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "connector_id", value)

    @_builtins.property
    @pulumi.getter(name="connectorIds")
    def connector_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The ID(s) of the connector(s) that the socket is attached to.
        """
        return pulumi.get(self, "connector_ids")

    @connector_ids.setter
    def connector_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "connector_ids", value)

    @_builtins.property
    @pulumi.getter(name="databaseConfigurations")
    def database_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketDatabaseConfigurationArgs']]]]:
        return pulumi.get(self, "database_configurations")

    @database_configurations.setter
    def database_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketDatabaseConfigurationArgs']]]]):
        pulumi.set(self, "database_configurations", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The description of the socket.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        An additional display name of the socket. Less restrictive than the `name` field and does not need to be unique.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter(name="elasticsearchConfigurations")
    def elasticsearch_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketElasticsearchConfigurationArgs']]]]:
        return pulumi.get(self, "elasticsearch_configurations")

    @elasticsearch_configurations.setter
    def elasticsearch_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketElasticsearchConfigurationArgs']]]]):
        pulumi.set(self, "elasticsearch_configurations", value)

    @_builtins.property
    @pulumi.getter(name="exitNodeConfigurations")
    def exit_node_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketExitNodeConfigurationArgs']]]]:
        return pulumi.get(self, "exit_node_configurations")

    @exit_node_configurations.setter
    def exit_node_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketExitNodeConfigurationArgs']]]]):
        pulumi.set(self, "exit_node_configurations", value)

    @_builtins.property
    @pulumi.getter(name="httpConfigurations")
    def http_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketHttpConfigurationArgs']]]]:
        return pulumi.get(self, "http_configurations")

    @http_configurations.setter
    def http_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketHttpConfigurationArgs']]]]):
        pulumi.set(self, "http_configurations", value)

    @_builtins.property
    @pulumi.getter(name="kubernetesConfigurations")
    def kubernetes_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketKubernetesConfigurationArgs']]]]:
        return pulumi.get(self, "kubernetes_configurations")

    @kubernetes_configurations.setter
    def kubernetes_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketKubernetesConfigurationArgs']]]]):
        pulumi.set(self, "kubernetes_configurations", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the socket. Must be unique within your Border0 organization. Socket name can have alphanumerics and hyphens,
        but it must start or end with alphanumeric.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="rdpConfigurations")
    def rdp_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketRdpConfigurationArgs']]]]:
        return pulumi.get(self, "rdp_configurations")

    @rdp_configurations.setter
    def rdp_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketRdpConfigurationArgs']]]]):
        pulumi.set(self, "rdp_configurations", value)

    @_builtins.property
    @pulumi.getter(name="recordingEnabled")
    def recording_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Indicates if session recording is enabled for the socket.
        """
        return pulumi.get(self, "recording_enabled")

    @recording_enabled.setter
    def recording_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "recording_enabled", value)

    @_builtins.property
    @pulumi.getter(name="snowflakeConfigurations")
    def snowflake_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketSnowflakeConfigurationArgs']]]]:
        return pulumi.get(self, "snowflake_configurations")

    @snowflake_configurations.setter
    def snowflake_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketSnowflakeConfigurationArgs']]]]):
        pulumi.set(self, "snowflake_configurations", value)

    @_builtins.property
    @pulumi.getter(name="socketId")
    def socket_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "socket_id")

    @socket_id.setter
    def socket_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "socket_id", value)

    @_builtins.property
    @pulumi.getter(name="socketType")
    def socket_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The type of the socket. Valid values: `ssh`, `http`, `database`, `tls`, `vnc`, `rdp`, `subnet_router`, `exit_node`,
        `snowflake`, `elasticsearch`, `kubernetes`, `aws_s3`.
        """
        return pulumi.get(self, "socket_type")

    @socket_type.setter
    def socket_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "socket_type", value)

    @_builtins.property
    @pulumi.getter(name="sshConfigurations")
    def ssh_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketSshConfigurationArgs']]]]:
        return pulumi.get(self, "ssh_configurations")

    @ssh_configurations.setter
    def ssh_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketSshConfigurationArgs']]]]):
        pulumi.set(self, "ssh_configurations", value)

    @_builtins.property
    @pulumi.getter(name="subnetRouterConfigurations")
    def subnet_router_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketSubnetRouterConfigurationArgs']]]]:
        return pulumi.get(self, "subnet_router_configurations")

    @subnet_router_configurations.setter
    def subnet_router_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketSubnetRouterConfigurationArgs']]]]):
        pulumi.set(self, "subnet_router_configurations", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        The tags of the socket.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tlsConfigurations")
    def tls_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketTlsConfigurationArgs']]]]:
        return pulumi.get(self, "tls_configurations")

    @tls_configurations.setter
    def tls_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketTlsConfigurationArgs']]]]):
        pulumi.set(self, "tls_configurations", value)

    @_builtins.property
    @pulumi.getter(name="upstreamType")
    def upstream_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The upstream type of the socket.
        """
        return pulumi.get(self, "upstream_type")

    @upstream_type.setter
    def upstream_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "upstream_type", value)

    @_builtins.property
    @pulumi.getter(name="vncConfigurations")
    def vnc_configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SocketVncConfigurationArgs']]]]:
        return pulumi.get(self, "vnc_configurations")

    @vnc_configurations.setter
    def vnc_configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SocketVncConfigurationArgs']]]]):
        pulumi.set(self, "vnc_configurations", value)


@pulumi.type_token("border0:index/socket:Socket")
class Socket(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 aws_s3_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketAwsS3ConfigurationArgs', 'SocketAwsS3ConfigurationArgsDict']]]]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 database_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketDatabaseConfigurationArgs', 'SocketDatabaseConfigurationArgsDict']]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 elasticsearch_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketElasticsearchConfigurationArgs', 'SocketElasticsearchConfigurationArgsDict']]]]] = None,
                 exit_node_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketExitNodeConfigurationArgs', 'SocketExitNodeConfigurationArgsDict']]]]] = None,
                 http_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketHttpConfigurationArgs', 'SocketHttpConfigurationArgsDict']]]]] = None,
                 kubernetes_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketKubernetesConfigurationArgs', 'SocketKubernetesConfigurationArgsDict']]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 rdp_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketRdpConfigurationArgs', 'SocketRdpConfigurationArgsDict']]]]] = None,
                 recording_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 snowflake_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketSnowflakeConfigurationArgs', 'SocketSnowflakeConfigurationArgsDict']]]]] = None,
                 socket_id: Optional[pulumi.Input[_builtins.str]] = None,
                 socket_type: Optional[pulumi.Input[_builtins.str]] = None,
                 ssh_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketSshConfigurationArgs', 'SocketSshConfigurationArgsDict']]]]] = None,
                 subnet_router_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketSubnetRouterConfigurationArgs', 'SocketSubnetRouterConfigurationArgsDict']]]]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tls_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketTlsConfigurationArgs', 'SocketTlsConfigurationArgsDict']]]]] = None,
                 upstream_type: Optional[pulumi.Input[_builtins.str]] = None,
                 vnc_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketVncConfigurationArgs', 'SocketVncConfigurationArgsDict']]]]] = None,
                 __props__=None):
        """
        Create a Socket resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] connector_id: The ID of the connector that the socket is attached to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] connector_ids: The ID(s) of the connector(s) that the socket is attached to.
        :param pulumi.Input[_builtins.str] description: The description of the socket.
        :param pulumi.Input[_builtins.str] display_name: An additional display name of the socket. Less restrictive than the `name` field and does not need to be unique.
        :param pulumi.Input[_builtins.str] name: The name of the socket. Must be unique within your Border0 organization. Socket name can have alphanumerics and hyphens,
               but it must start or end with alphanumeric.
        :param pulumi.Input[_builtins.bool] recording_enabled: Indicates if session recording is enabled for the socket.
        :param pulumi.Input[_builtins.str] socket_type: The type of the socket. Valid values: `ssh`, `http`, `database`, `tls`, `vnc`, `rdp`, `subnet_router`, `exit_node`,
               `snowflake`, `elasticsearch`, `kubernetes`, `aws_s3`.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: The tags of the socket.
        :param pulumi.Input[_builtins.str] upstream_type: The upstream type of the socket.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SocketArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Socket resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param SocketArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SocketArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 aws_s3_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketAwsS3ConfigurationArgs', 'SocketAwsS3ConfigurationArgsDict']]]]] = None,
                 connector_id: Optional[pulumi.Input[_builtins.str]] = None,
                 connector_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 database_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketDatabaseConfigurationArgs', 'SocketDatabaseConfigurationArgsDict']]]]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 elasticsearch_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketElasticsearchConfigurationArgs', 'SocketElasticsearchConfigurationArgsDict']]]]] = None,
                 exit_node_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketExitNodeConfigurationArgs', 'SocketExitNodeConfigurationArgsDict']]]]] = None,
                 http_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketHttpConfigurationArgs', 'SocketHttpConfigurationArgsDict']]]]] = None,
                 kubernetes_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketKubernetesConfigurationArgs', 'SocketKubernetesConfigurationArgsDict']]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 rdp_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketRdpConfigurationArgs', 'SocketRdpConfigurationArgsDict']]]]] = None,
                 recording_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 snowflake_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketSnowflakeConfigurationArgs', 'SocketSnowflakeConfigurationArgsDict']]]]] = None,
                 socket_id: Optional[pulumi.Input[_builtins.str]] = None,
                 socket_type: Optional[pulumi.Input[_builtins.str]] = None,
                 ssh_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketSshConfigurationArgs', 'SocketSshConfigurationArgsDict']]]]] = None,
                 subnet_router_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketSubnetRouterConfigurationArgs', 'SocketSubnetRouterConfigurationArgsDict']]]]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tls_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketTlsConfigurationArgs', 'SocketTlsConfigurationArgsDict']]]]] = None,
                 upstream_type: Optional[pulumi.Input[_builtins.str]] = None,
                 vnc_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketVncConfigurationArgs', 'SocketVncConfigurationArgsDict']]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SocketArgs.__new__(SocketArgs)

            __props__.__dict__["aws_s3_configurations"] = aws_s3_configurations
            __props__.__dict__["connector_id"] = connector_id
            __props__.__dict__["connector_ids"] = connector_ids
            __props__.__dict__["database_configurations"] = database_configurations
            __props__.__dict__["description"] = description
            __props__.__dict__["display_name"] = display_name
            __props__.__dict__["elasticsearch_configurations"] = elasticsearch_configurations
            __props__.__dict__["exit_node_configurations"] = exit_node_configurations
            __props__.__dict__["http_configurations"] = http_configurations
            __props__.__dict__["kubernetes_configurations"] = kubernetes_configurations
            __props__.__dict__["name"] = name
            __props__.__dict__["rdp_configurations"] = rdp_configurations
            __props__.__dict__["recording_enabled"] = recording_enabled
            __props__.__dict__["snowflake_configurations"] = snowflake_configurations
            __props__.__dict__["socket_id"] = socket_id
            if socket_type is None and not opts.urn:
                raise TypeError("Missing required property 'socket_type'")
            __props__.__dict__["socket_type"] = socket_type
            __props__.__dict__["ssh_configurations"] = ssh_configurations
            __props__.__dict__["subnet_router_configurations"] = subnet_router_configurations
            __props__.__dict__["tags"] = tags
            __props__.__dict__["tls_configurations"] = tls_configurations
            __props__.__dict__["upstream_type"] = upstream_type
            __props__.__dict__["vnc_configurations"] = vnc_configurations
        super(Socket, __self__).__init__(
            'border0:index/socket:Socket',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            aws_s3_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketAwsS3ConfigurationArgs', 'SocketAwsS3ConfigurationArgsDict']]]]] = None,
            connector_id: Optional[pulumi.Input[_builtins.str]] = None,
            connector_ids: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            database_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketDatabaseConfigurationArgs', 'SocketDatabaseConfigurationArgsDict']]]]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            display_name: Optional[pulumi.Input[_builtins.str]] = None,
            elasticsearch_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketElasticsearchConfigurationArgs', 'SocketElasticsearchConfigurationArgsDict']]]]] = None,
            exit_node_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketExitNodeConfigurationArgs', 'SocketExitNodeConfigurationArgsDict']]]]] = None,
            http_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketHttpConfigurationArgs', 'SocketHttpConfigurationArgsDict']]]]] = None,
            kubernetes_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketKubernetesConfigurationArgs', 'SocketKubernetesConfigurationArgsDict']]]]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            rdp_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketRdpConfigurationArgs', 'SocketRdpConfigurationArgsDict']]]]] = None,
            recording_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
            snowflake_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketSnowflakeConfigurationArgs', 'SocketSnowflakeConfigurationArgsDict']]]]] = None,
            socket_id: Optional[pulumi.Input[_builtins.str]] = None,
            socket_type: Optional[pulumi.Input[_builtins.str]] = None,
            ssh_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketSshConfigurationArgs', 'SocketSshConfigurationArgsDict']]]]] = None,
            subnet_router_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketSubnetRouterConfigurationArgs', 'SocketSubnetRouterConfigurationArgsDict']]]]] = None,
            tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            tls_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketTlsConfigurationArgs', 'SocketTlsConfigurationArgsDict']]]]] = None,
            upstream_type: Optional[pulumi.Input[_builtins.str]] = None,
            vnc_configurations: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SocketVncConfigurationArgs', 'SocketVncConfigurationArgsDict']]]]] = None) -> 'Socket':
        """
        Get an existing Socket resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] connector_id: The ID of the connector that the socket is attached to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] connector_ids: The ID(s) of the connector(s) that the socket is attached to.
        :param pulumi.Input[_builtins.str] description: The description of the socket.
        :param pulumi.Input[_builtins.str] display_name: An additional display name of the socket. Less restrictive than the `name` field and does not need to be unique.
        :param pulumi.Input[_builtins.str] name: The name of the socket. Must be unique within your Border0 organization. Socket name can have alphanumerics and hyphens,
               but it must start or end with alphanumeric.
        :param pulumi.Input[_builtins.bool] recording_enabled: Indicates if session recording is enabled for the socket.
        :param pulumi.Input[_builtins.str] socket_type: The type of the socket. Valid values: `ssh`, `http`, `database`, `tls`, `vnc`, `rdp`, `subnet_router`, `exit_node`,
               `snowflake`, `elasticsearch`, `kubernetes`, `aws_s3`.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: The tags of the socket.
        :param pulumi.Input[_builtins.str] upstream_type: The upstream type of the socket.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SocketState.__new__(_SocketState)

        __props__.__dict__["aws_s3_configurations"] = aws_s3_configurations
        __props__.__dict__["connector_id"] = connector_id
        __props__.__dict__["connector_ids"] = connector_ids
        __props__.__dict__["database_configurations"] = database_configurations
        __props__.__dict__["description"] = description
        __props__.__dict__["display_name"] = display_name
        __props__.__dict__["elasticsearch_configurations"] = elasticsearch_configurations
        __props__.__dict__["exit_node_configurations"] = exit_node_configurations
        __props__.__dict__["http_configurations"] = http_configurations
        __props__.__dict__["kubernetes_configurations"] = kubernetes_configurations
        __props__.__dict__["name"] = name
        __props__.__dict__["rdp_configurations"] = rdp_configurations
        __props__.__dict__["recording_enabled"] = recording_enabled
        __props__.__dict__["snowflake_configurations"] = snowflake_configurations
        __props__.__dict__["socket_id"] = socket_id
        __props__.__dict__["socket_type"] = socket_type
        __props__.__dict__["ssh_configurations"] = ssh_configurations
        __props__.__dict__["subnet_router_configurations"] = subnet_router_configurations
        __props__.__dict__["tags"] = tags
        __props__.__dict__["tls_configurations"] = tls_configurations
        __props__.__dict__["upstream_type"] = upstream_type
        __props__.__dict__["vnc_configurations"] = vnc_configurations
        return Socket(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="awsS3Configurations")
    def aws_s3_configurations(self) -> pulumi.Output[Optional[Sequence['outputs.SocketAwsS3Configuration']]]:
        return pulumi.get(self, "aws_s3_configurations")

    @_builtins.property
    @pulumi.getter(name="connectorId")
    @_utilities.deprecated("""Deprecated""")
    def connector_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The ID of the connector that the socket is attached to.
        """
        return pulumi.get(self, "connector_id")

    @_builtins.property
    @pulumi.getter(name="connectorIds")
    def connector_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        The ID(s) of the connector(s) that the socket is attached to.
        """
        return pulumi.get(self, "connector_ids")

    @_builtins.property
    @pulumi.getter(name="databaseConfigurations")
    def database_configurations(self) -> pulumi.Output[Optional[Sequence['outputs.SocketDatabaseConfiguration']]]:
        return pulumi.get(self, "database_configurations")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The description of the socket.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        An additional display name of the socket. Less restrictive than the `name` field and does not need to be unique.
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter(name="elasticsearchConfigurations")
    def elasticsearch_configurations(self) -> pulumi.Output[Optional[Sequence['outputs.SocketElasticsearchConfiguration']]]:
        return pulumi.get(self, "elasticsearch_configurations")

    @_builtins.property
    @pulumi.getter(name="exitNodeConfigurations")
    def exit_node_configurations(self) -> pulumi.Output[Optional[Sequence['outputs.SocketExitNodeConfiguration']]]:
        return pulumi.get(self, "exit_node_configurations")

    @_builtins.property
    @pulumi.getter(name="httpConfigurations")
    def http_configurations(self) -> pulumi.Output[Optional[Sequence['outputs.SocketHttpConfiguration']]]:
        return pulumi.get(self, "http_configurations")

    @_builtins.property
    @pulumi.getter(name="kubernetesConfigurations")
    def kubernetes_configurations(self) -> pulumi.Output[Optional[Sequence['outputs.SocketKubernetesConfiguration']]]:
        return pulumi.get(self, "kubernetes_configurations")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the socket. Must be unique within your Border0 organization. Socket name can have alphanumerics and hyphens,
        but it must start or end with alphanumeric.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="rdpConfigurations")
    def rdp_configurations(self) -> pulumi.Output[Optional[Sequence['outputs.SocketRdpConfiguration']]]:
        return pulumi.get(self, "rdp_configurations")

    @_builtins.property
    @pulumi.getter(name="recordingEnabled")
    def recording_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Indicates if session recording is enabled for the socket.
        """
        return pulumi.get(self, "recording_enabled")

    @_builtins.property
    @pulumi.getter(name="snowflakeConfigurations")
    def snowflake_configurations(self) -> pulumi.Output[Optional[Sequence['outputs.SocketSnowflakeConfiguration']]]:
        return pulumi.get(self, "snowflake_configurations")

    @_builtins.property
    @pulumi.getter(name="socketId")
    def socket_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "socket_id")

    @_builtins.property
    @pulumi.getter(name="socketType")
    def socket_type(self) -> pulumi.Output[_builtins.str]:
        """
        The type of the socket. Valid values: `ssh`, `http`, `database`, `tls`, `vnc`, `rdp`, `subnet_router`, `exit_node`,
        `snowflake`, `elasticsearch`, `kubernetes`, `aws_s3`.
        """
        return pulumi.get(self, "socket_type")

    @_builtins.property
    @pulumi.getter(name="sshConfigurations")
    def ssh_configurations(self) -> pulumi.Output[Optional[Sequence['outputs.SocketSshConfiguration']]]:
        return pulumi.get(self, "ssh_configurations")

    @_builtins.property
    @pulumi.getter(name="subnetRouterConfigurations")
    def subnet_router_configurations(self) -> pulumi.Output[Optional[Sequence['outputs.SocketSubnetRouterConfiguration']]]:
        return pulumi.get(self, "subnet_router_configurations")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        The tags of the socket.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="tlsConfigurations")
    def tls_configurations(self) -> pulumi.Output[Optional[Sequence['outputs.SocketTlsConfiguration']]]:
        return pulumi.get(self, "tls_configurations")

    @_builtins.property
    @pulumi.getter(name="upstreamType")
    def upstream_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The upstream type of the socket.
        """
        return pulumi.get(self, "upstream_type")

    @_builtins.property
    @pulumi.getter(name="vncConfigurations")
    def vnc_configurations(self) -> pulumi.Output[Optional[Sequence['outputs.SocketVncConfiguration']]]:
        return pulumi.get(self, "vnc_configurations")

