# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ContactsArgs', 'Contacts']

@pulumi.input_type
class ContactsArgs:
    def __init__(__self__, *,
                 accounts: Optional[pulumi.Input[Sequence[pulumi.Input['ContactsAccountArgs']]]] = None,
                 securities: Optional[pulumi.Input[Sequence[pulumi.Input['ContactsSecurityArgs']]]] = None,
                 supports: Optional[pulumi.Input[Sequence[pulumi.Input['ContactsSupportArgs']]]] = None):
        """
        The set of arguments for constructing a Contacts resource.

        :param pulumi.Input[Sequence[pulumi.Input['ContactsAccountArgs']]] accounts: Configuration for communications about important changes to your tailnet
        :param pulumi.Input[Sequence[pulumi.Input['ContactsSecurityArgs']]] securities: Configuration for communications about security issues affecting your tailnet
        :param pulumi.Input[Sequence[pulumi.Input['ContactsSupportArgs']]] supports: Configuration for communications about misconfigurations in your tailnet
        """
        if accounts is not None:
            pulumi.set(__self__, "accounts", accounts)
        if securities is not None:
            pulumi.set(__self__, "securities", securities)
        if supports is not None:
            pulumi.set(__self__, "supports", supports)

    @_builtins.property
    @pulumi.getter
    def accounts(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ContactsAccountArgs']]]]:
        """
        Configuration for communications about important changes to your tailnet
        """
        return pulumi.get(self, "accounts")

    @accounts.setter
    def accounts(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ContactsAccountArgs']]]]):
        pulumi.set(self, "accounts", value)

    @_builtins.property
    @pulumi.getter
    def securities(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ContactsSecurityArgs']]]]:
        """
        Configuration for communications about security issues affecting your tailnet
        """
        return pulumi.get(self, "securities")

    @securities.setter
    def securities(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ContactsSecurityArgs']]]]):
        pulumi.set(self, "securities", value)

    @_builtins.property
    @pulumi.getter
    def supports(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ContactsSupportArgs']]]]:
        """
        Configuration for communications about misconfigurations in your tailnet
        """
        return pulumi.get(self, "supports")

    @supports.setter
    def supports(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ContactsSupportArgs']]]]):
        pulumi.set(self, "supports", value)


@pulumi.input_type
class _ContactsState:
    def __init__(__self__, *,
                 accounts: Optional[pulumi.Input[Sequence[pulumi.Input['ContactsAccountArgs']]]] = None,
                 securities: Optional[pulumi.Input[Sequence[pulumi.Input['ContactsSecurityArgs']]]] = None,
                 supports: Optional[pulumi.Input[Sequence[pulumi.Input['ContactsSupportArgs']]]] = None):
        """
        Input properties used for looking up and filtering Contacts resources.

        :param pulumi.Input[Sequence[pulumi.Input['ContactsAccountArgs']]] accounts: Configuration for communications about important changes to your tailnet
        :param pulumi.Input[Sequence[pulumi.Input['ContactsSecurityArgs']]] securities: Configuration for communications about security issues affecting your tailnet
        :param pulumi.Input[Sequence[pulumi.Input['ContactsSupportArgs']]] supports: Configuration for communications about misconfigurations in your tailnet
        """
        if accounts is not None:
            pulumi.set(__self__, "accounts", accounts)
        if securities is not None:
            pulumi.set(__self__, "securities", securities)
        if supports is not None:
            pulumi.set(__self__, "supports", supports)

    @_builtins.property
    @pulumi.getter
    def accounts(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ContactsAccountArgs']]]]:
        """
        Configuration for communications about important changes to your tailnet
        """
        return pulumi.get(self, "accounts")

    @accounts.setter
    def accounts(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ContactsAccountArgs']]]]):
        pulumi.set(self, "accounts", value)

    @_builtins.property
    @pulumi.getter
    def securities(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ContactsSecurityArgs']]]]:
        """
        Configuration for communications about security issues affecting your tailnet
        """
        return pulumi.get(self, "securities")

    @securities.setter
    def securities(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ContactsSecurityArgs']]]]):
        pulumi.set(self, "securities", value)

    @_builtins.property
    @pulumi.getter
    def supports(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ContactsSupportArgs']]]]:
        """
        Configuration for communications about misconfigurations in your tailnet
        """
        return pulumi.get(self, "supports")

    @supports.setter
    def supports(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ContactsSupportArgs']]]]):
        pulumi.set(self, "supports", value)


@pulumi.type_token("tailscale:index/contacts:Contacts")
class Contacts(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 accounts: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ContactsAccountArgs', 'ContactsAccountArgsDict']]]]] = None,
                 securities: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ContactsSecurityArgs', 'ContactsSecurityArgsDict']]]]] = None,
                 supports: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ContactsSupportArgs', 'ContactsSupportArgsDict']]]]] = None,
                 __props__=None):
        """
        Create a Contacts resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ContactsAccountArgs', 'ContactsAccountArgsDict']]]] accounts: Configuration for communications about important changes to your tailnet
        :param pulumi.Input[Sequence[pulumi.Input[Union['ContactsSecurityArgs', 'ContactsSecurityArgsDict']]]] securities: Configuration for communications about security issues affecting your tailnet
        :param pulumi.Input[Sequence[pulumi.Input[Union['ContactsSupportArgs', 'ContactsSupportArgsDict']]]] supports: Configuration for communications about misconfigurations in your tailnet
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ContactsArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Contacts resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ContactsArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ContactsArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 accounts: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ContactsAccountArgs', 'ContactsAccountArgsDict']]]]] = None,
                 securities: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ContactsSecurityArgs', 'ContactsSecurityArgsDict']]]]] = None,
                 supports: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ContactsSupportArgs', 'ContactsSupportArgsDict']]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ContactsArgs.__new__(ContactsArgs)

            __props__.__dict__["accounts"] = accounts
            __props__.__dict__["securities"] = securities
            __props__.__dict__["supports"] = supports
        super(Contacts, __self__).__init__(
            'tailscale:index/contacts:Contacts',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            accounts: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ContactsAccountArgs', 'ContactsAccountArgsDict']]]]] = None,
            securities: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ContactsSecurityArgs', 'ContactsSecurityArgsDict']]]]] = None,
            supports: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ContactsSupportArgs', 'ContactsSupportArgsDict']]]]] = None) -> 'Contacts':
        """
        Get an existing Contacts resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ContactsAccountArgs', 'ContactsAccountArgsDict']]]] accounts: Configuration for communications about important changes to your tailnet
        :param pulumi.Input[Sequence[pulumi.Input[Union['ContactsSecurityArgs', 'ContactsSecurityArgsDict']]]] securities: Configuration for communications about security issues affecting your tailnet
        :param pulumi.Input[Sequence[pulumi.Input[Union['ContactsSupportArgs', 'ContactsSupportArgsDict']]]] supports: Configuration for communications about misconfigurations in your tailnet
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ContactsState.__new__(_ContactsState)

        __props__.__dict__["accounts"] = accounts
        __props__.__dict__["securities"] = securities
        __props__.__dict__["supports"] = supports
        return Contacts(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def accounts(self) -> pulumi.Output[Optional[Sequence['outputs.ContactsAccount']]]:
        """
        Configuration for communications about important changes to your tailnet
        """
        return pulumi.get(self, "accounts")

    @_builtins.property
    @pulumi.getter
    def securities(self) -> pulumi.Output[Optional[Sequence['outputs.ContactsSecurity']]]:
        """
        Configuration for communications about security issues affecting your tailnet
        """
        return pulumi.get(self, "securities")

    @_builtins.property
    @pulumi.getter
    def supports(self) -> pulumi.Output[Optional[Sequence['outputs.ContactsSupport']]]:
        """
        Configuration for communications about misconfigurations in your tailnet
        """
        return pulumi.get(self, "supports")

