# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'Get4via6Result',
    'AwaitableGet4via6Result',
    'get4via6',
    'get4via6_output',
]

@pulumi.output_type
class Get4via6Result:
    """
    A collection of values returned by get4via6.
    """
    def __init__(__self__, cidr=None, id=None, ipv6=None, site=None):
        if cidr and not isinstance(cidr, str):
            raise TypeError("Expected argument 'cidr' to be a str")
        pulumi.set(__self__, "cidr", cidr)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if ipv6 and not isinstance(ipv6, str):
            raise TypeError("Expected argument 'ipv6' to be a str")
        pulumi.set(__self__, "ipv6", ipv6)
        if site and not isinstance(site, float):
            raise TypeError("Expected argument 'site' to be a float")
        pulumi.set(__self__, "site", site)

    @_builtins.property
    @pulumi.getter
    def cidr(self) -> _builtins.str:
        return pulumi.get(self, "cidr")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def ipv6(self) -> _builtins.str:
        return pulumi.get(self, "ipv6")

    @_builtins.property
    @pulumi.getter
    def site(self) -> _builtins.float:
        return pulumi.get(self, "site")


class AwaitableGet4via6Result(Get4via6Result):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return Get4via6Result(
            cidr=self.cidr,
            id=self.id,
            ipv6=self.ipv6,
            site=self.site)


def get4via6(cidr: Optional[_builtins.str] = None,
             site: Optional[_builtins.float] = None,
             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGet4via6Result:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['cidr'] = cidr
    __args__['site'] = site
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('tailscale:index/get4via6:get4via6', __args__, opts=opts, typ=Get4via6Result, package_ref=_utilities.get_package()).value

    return AwaitableGet4via6Result(
        cidr=pulumi.get(__ret__, 'cidr'),
        id=pulumi.get(__ret__, 'id'),
        ipv6=pulumi.get(__ret__, 'ipv6'),
        site=pulumi.get(__ret__, 'site'))
def get4via6_output(cidr: Optional[pulumi.Input[_builtins.str]] = None,
                    site: Optional[pulumi.Input[_builtins.float]] = None,
                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[Get4via6Result]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['cidr'] = cidr
    __args__['site'] = site
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('tailscale:index/get4via6:get4via6', __args__, opts=opts, typ=Get4via6Result, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: Get4via6Result(
        cidr=pulumi.get(__response__, 'cidr'),
        id=pulumi.get(__response__, 'id'),
        ipv6=pulumi.get(__response__, 'ipv6'),
        site=pulumi.get(__response__, 'site')))
