# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._inputs import *

__all__ = ['ModuleArgs', 'Module']

@pulumi.input_type
class ModuleArgs:
    def __init__(__self__, *,
                 accept_dns: Optional[pulumi.Input[_builtins.bool]] = None,
                 accept_routes: Optional[pulumi.Input[_builtins.bool]] = None,
                 additional_parts: Optional[pulumi.Input[Sequence[pulumi.Input['AdditionalPartsArgs']]]] = None,
                 advertise_connector: Optional[pulumi.Input[_builtins.bool]] = None,
                 advertise_exit_node: Optional[pulumi.Input[_builtins.bool]] = None,
                 advertise_routes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 advertise_tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 audience: Optional[pulumi.Input[_builtins.str]] = None,
                 auth_key: Optional[pulumi.Input[_builtins.str]] = None,
                 base64_encode: Optional[pulumi.Input[_builtins.bool]] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_ssh: Optional[pulumi.Input[_builtins.bool]] = None,
                 exit_node: Optional[pulumi.Input[_builtins.str]] = None,
                 exit_node_allow_lan_access: Optional[pulumi.Input[_builtins.bool]] = None,
                 force_reauth: Optional[pulumi.Input[_builtins.bool]] = None,
                 gzip: Optional[pulumi.Input[_builtins.bool]] = None,
                 hostname: Optional[pulumi.Input[_builtins.str]] = None,
                 id_token: Optional[pulumi.Input[_builtins.str]] = None,
                 json: Optional[pulumi.Input[_builtins.bool]] = None,
                 login_server: Optional[pulumi.Input[_builtins.str]] = None,
                 max_retries: Optional[pulumi.Input[_builtins.float]] = None,
                 netfilter_mode: Optional[pulumi.Input[_builtins.str]] = None,
                 operator: Optional[pulumi.Input[_builtins.str]] = None,
                 relay_server_port: Optional[pulumi.Input[_builtins.float]] = None,
                 reset: Optional[pulumi.Input[_builtins.bool]] = None,
                 retry_delay: Optional[pulumi.Input[_builtins.float]] = None,
                 shields_up: Optional[pulumi.Input[_builtins.bool]] = None,
                 snat_subnet_routes: Optional[pulumi.Input[_builtins.bool]] = None,
                 stateful_filtering: Optional[pulumi.Input[_builtins.bool]] = None,
                 tailscaled_flag_bird_socket: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_config: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_debug: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_encrypt_state: Optional[pulumi.Input[_builtins.bool]] = None,
                 tailscaled_flag_no_logs_no_support: Optional[pulumi.Input[_builtins.bool]] = None,
                 tailscaled_flag_outbound_http_proxy_listen: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_port: Optional[pulumi.Input[_builtins.float]] = None,
                 tailscaled_flag_socket: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_socks5_server: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_state: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_statedir: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_tun: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_verbose: Optional[pulumi.Input[_builtins.float]] = None,
                 timeout: Optional[pulumi.Input[_builtins.str]] = None,
                 track: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Module resource.

        :param pulumi.Input[_builtins.bool] accept_dns: Accept DNS configuration from Tailscale
        :param pulumi.Input[_builtins.bool] accept_routes: Accept routes from Tailscale
        :param pulumi.Input[Sequence[pulumi.Input['AdditionalPartsArgs']]] additional_parts: Additional user defined part blocks for the cloudinit_config data source
        :param pulumi.Input[_builtins.bool] advertise_connector: Advertise this node as an app connector
        :param pulumi.Input[_builtins.bool] advertise_exit_node: Offer to be an exit node for internet traffic for the tailnet
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] advertise_routes: Routes to advertise to other nodes
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] advertise_tags: ACL tags to request; each must start with 'tag:' (e.g. 'tag:eng,tag:montreal,tag:ssh')
        :param pulumi.Input[_builtins.str] audience: Audience used when requesting an ID token from an identity provider for auth keys generated by workload identity federation.
        :param pulumi.Input[_builtins.str] auth_key: Node authorization key; if it begins with 'file:', then it's a path to a file containing the authkey; if it begins with 'command:', then it's a command to execute that outputs the authkey
        :param pulumi.Input[_builtins.bool] base64_encode: Whether to base64 encode the cloud-init data
        :param pulumi.Input[_builtins.str] client_id: Client ID used to generate authkeys via workload identity federation
        :param pulumi.Input[_builtins.str] client_secret: Client Secret used to generate authkeys via OAuth; if it begins with "file:", then it's a path to a file containing the secret; if it begins with "command:", then it's a command to execute that outputs the secret
        :param pulumi.Input[_builtins.bool] enable_ssh: Enable SSH access via Tailscale
        :param pulumi.Input[_builtins.str] exit_node: Tailscale exit node (IP or base name) for internet traffic
        :param pulumi.Input[_builtins.bool] exit_node_allow_lan_access: Allow direct access to the local network when routing traffic via an exit node
        :param pulumi.Input[_builtins.bool] force_reauth: force reauthentication
        :param pulumi.Input[_builtins.bool] gzip: Whether to gzip the cloud-init data
        :param pulumi.Input[_builtins.str] hostname: Hostname of the instance
        :param pulumi.Input[_builtins.str] id_token: ID token from the identity provider to exchange with the control server for workload identity federation; if it begins with "file:", then it's a path to a file containing the token; if it begins with "command:", then it's a command to execute that outputs the token
        :param pulumi.Input[_builtins.bool] json: output in JSON format
        :param pulumi.Input[_builtins.str] login_server: base URL of control server
        :param pulumi.Input[_builtins.float] max_retries: maximum number of retries to connect to the control server
        :param pulumi.Input[_builtins.str] netfilter_mode: netfilter mode
        :param pulumi.Input[_builtins.str] operator: Unix username to allow to operate on tailscaled without sudo
        :param pulumi.Input[_builtins.float] relay_server_port: Port for the Tailscale relay server; when null, peer relay advertisement is not configured
        :param pulumi.Input[_builtins.bool] reset: reset unspecified settings to their default values
        :param pulumi.Input[_builtins.float] retry_delay: delay in seconds between retries to connect to the control server
        :param pulumi.Input[_builtins.bool] shields_up: don't allow incoming connections
        :param pulumi.Input[_builtins.bool] snat_subnet_routes: source NAT traffic to local routes advertised with --advertise-routes
        :param pulumi.Input[_builtins.bool] stateful_filtering: apply stateful filtering to forwarded packets
        :param pulumi.Input[_builtins.str] tailscaled_flag_bird_socket: path of the bird unix socket
        :param pulumi.Input[_builtins.str] tailscaled_flag_config: path to config file, or 'vm:user-data' to use the VM's user-data (EC2)
        :param pulumi.Input[_builtins.str] tailscaled_flag_debug: listen address ([ip]:port) of optional debug server
        :param pulumi.Input[_builtins.bool] tailscaled_flag_encrypt_state: encrypt the state file on disk; uses TPM on Linux and Windows
        :param pulumi.Input[_builtins.bool] tailscaled_flag_no_logs_no_support: disable log uploads; this also disables any technical support
        :param pulumi.Input[_builtins.str] tailscaled_flag_outbound_http_proxy_listen: optional [ip]:port to run an outbound HTTP proxy (e.g. "localhost:8080")
        :param pulumi.Input[_builtins.float] tailscaled_flag_port: UDP port to listen on for WireGuard and peer-to-peer traffic; 0 means automatically select
        :param pulumi.Input[_builtins.str] tailscaled_flag_socket: path of the service unix socket
        :param pulumi.Input[_builtins.str] tailscaled_flag_socks5_server: optional [ip]:port to run a SOCK5 server (e.g. "localhost:1080")
        :param pulumi.Input[_builtins.str] tailscaled_flag_state: absolute path of state file; use 'kube:<secret-name>' to use Kubernetes secrets or 'arn:aws:ssm:...' to store in AWS SSM; use 'mem:' to not store state and register as an ephemeral node
        :param pulumi.Input[_builtins.str] tailscaled_flag_statedir: path to directory for storage of config state, TLS certs, temporary incoming Taildrop files, etc.
        :param pulumi.Input[_builtins.str] tailscaled_flag_tun: tunnel interface name; use "userspace-networking" (beta) to not use TUN
        :param pulumi.Input[_builtins.float] tailscaled_flag_verbose: log verbosity level; 0 is default, 1 or higher are increasingly verbose
        :param pulumi.Input[_builtins.str] timeout: maximum amount of time to wait for tailscaled to enter a Running state
        :param pulumi.Input[_builtins.str] track: Version of the Tailscale client to install
        """
        if accept_dns is not None:
            pulumi.set(__self__, "accept_dns", accept_dns)
        if accept_routes is not None:
            pulumi.set(__self__, "accept_routes", accept_routes)
        if additional_parts is not None:
            pulumi.set(__self__, "additional_parts", additional_parts)
        if advertise_connector is not None:
            pulumi.set(__self__, "advertise_connector", advertise_connector)
        if advertise_exit_node is not None:
            pulumi.set(__self__, "advertise_exit_node", advertise_exit_node)
        if advertise_routes is not None:
            pulumi.set(__self__, "advertise_routes", advertise_routes)
        if advertise_tags is not None:
            pulumi.set(__self__, "advertise_tags", advertise_tags)
        if audience is not None:
            pulumi.set(__self__, "audience", audience)
        if auth_key is not None:
            pulumi.set(__self__, "auth_key", auth_key)
        if base64_encode is not None:
            pulumi.set(__self__, "base64_encode", base64_encode)
        if client_id is not None:
            pulumi.set(__self__, "client_id", client_id)
        if client_secret is not None:
            pulumi.set(__self__, "client_secret", client_secret)
        if enable_ssh is not None:
            pulumi.set(__self__, "enable_ssh", enable_ssh)
        if exit_node is not None:
            pulumi.set(__self__, "exit_node", exit_node)
        if exit_node_allow_lan_access is not None:
            pulumi.set(__self__, "exit_node_allow_lan_access", exit_node_allow_lan_access)
        if force_reauth is not None:
            pulumi.set(__self__, "force_reauth", force_reauth)
        if gzip is not None:
            pulumi.set(__self__, "gzip", gzip)
        if hostname is not None:
            pulumi.set(__self__, "hostname", hostname)
        if id_token is not None:
            pulumi.set(__self__, "id_token", id_token)
        if json is not None:
            pulumi.set(__self__, "json", json)
        if login_server is not None:
            pulumi.set(__self__, "login_server", login_server)
        if max_retries is not None:
            pulumi.set(__self__, "max_retries", max_retries)
        if netfilter_mode is not None:
            pulumi.set(__self__, "netfilter_mode", netfilter_mode)
        if operator is not None:
            pulumi.set(__self__, "operator", operator)
        if relay_server_port is not None:
            pulumi.set(__self__, "relay_server_port", relay_server_port)
        if reset is not None:
            pulumi.set(__self__, "reset", reset)
        if retry_delay is not None:
            pulumi.set(__self__, "retry_delay", retry_delay)
        if shields_up is not None:
            pulumi.set(__self__, "shields_up", shields_up)
        if snat_subnet_routes is not None:
            pulumi.set(__self__, "snat_subnet_routes", snat_subnet_routes)
        if stateful_filtering is not None:
            pulumi.set(__self__, "stateful_filtering", stateful_filtering)
        if tailscaled_flag_bird_socket is not None:
            pulumi.set(__self__, "tailscaled_flag_bird_socket", tailscaled_flag_bird_socket)
        if tailscaled_flag_config is not None:
            pulumi.set(__self__, "tailscaled_flag_config", tailscaled_flag_config)
        if tailscaled_flag_debug is not None:
            pulumi.set(__self__, "tailscaled_flag_debug", tailscaled_flag_debug)
        if tailscaled_flag_encrypt_state is not None:
            pulumi.set(__self__, "tailscaled_flag_encrypt_state", tailscaled_flag_encrypt_state)
        if tailscaled_flag_no_logs_no_support is not None:
            pulumi.set(__self__, "tailscaled_flag_no_logs_no_support", tailscaled_flag_no_logs_no_support)
        if tailscaled_flag_outbound_http_proxy_listen is not None:
            pulumi.set(__self__, "tailscaled_flag_outbound_http_proxy_listen", tailscaled_flag_outbound_http_proxy_listen)
        if tailscaled_flag_port is not None:
            pulumi.set(__self__, "tailscaled_flag_port", tailscaled_flag_port)
        if tailscaled_flag_socket is not None:
            pulumi.set(__self__, "tailscaled_flag_socket", tailscaled_flag_socket)
        if tailscaled_flag_socks5_server is not None:
            pulumi.set(__self__, "tailscaled_flag_socks5_server", tailscaled_flag_socks5_server)
        if tailscaled_flag_state is not None:
            pulumi.set(__self__, "tailscaled_flag_state", tailscaled_flag_state)
        if tailscaled_flag_statedir is not None:
            pulumi.set(__self__, "tailscaled_flag_statedir", tailscaled_flag_statedir)
        if tailscaled_flag_tun is not None:
            pulumi.set(__self__, "tailscaled_flag_tun", tailscaled_flag_tun)
        if tailscaled_flag_verbose is not None:
            pulumi.set(__self__, "tailscaled_flag_verbose", tailscaled_flag_verbose)
        if timeout is not None:
            pulumi.set(__self__, "timeout", timeout)
        if track is not None:
            pulumi.set(__self__, "track", track)

    @_builtins.property
    @pulumi.getter
    def accept_dns(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Accept DNS configuration from Tailscale
        """
        return pulumi.get(self, "accept_dns")

    @accept_dns.setter
    def accept_dns(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "accept_dns", value)

    @_builtins.property
    @pulumi.getter
    def accept_routes(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Accept routes from Tailscale
        """
        return pulumi.get(self, "accept_routes")

    @accept_routes.setter
    def accept_routes(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "accept_routes", value)

    @_builtins.property
    @pulumi.getter
    def additional_parts(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['AdditionalPartsArgs']]]]:
        """
        Additional user defined part blocks for the cloudinit_config data source
        """
        return pulumi.get(self, "additional_parts")

    @additional_parts.setter
    def additional_parts(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['AdditionalPartsArgs']]]]):
        pulumi.set(self, "additional_parts", value)

    @_builtins.property
    @pulumi.getter
    def advertise_connector(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Advertise this node as an app connector
        """
        return pulumi.get(self, "advertise_connector")

    @advertise_connector.setter
    def advertise_connector(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "advertise_connector", value)

    @_builtins.property
    @pulumi.getter
    def advertise_exit_node(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Offer to be an exit node for internet traffic for the tailnet
        """
        return pulumi.get(self, "advertise_exit_node")

    @advertise_exit_node.setter
    def advertise_exit_node(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "advertise_exit_node", value)

    @_builtins.property
    @pulumi.getter
    def advertise_routes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Routes to advertise to other nodes
        """
        return pulumi.get(self, "advertise_routes")

    @advertise_routes.setter
    def advertise_routes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "advertise_routes", value)

    @_builtins.property
    @pulumi.getter
    def advertise_tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        ACL tags to request; each must start with 'tag:' (e.g. 'tag:eng,tag:montreal,tag:ssh')
        """
        return pulumi.get(self, "advertise_tags")

    @advertise_tags.setter
    def advertise_tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "advertise_tags", value)

    @_builtins.property
    @pulumi.getter
    def audience(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Audience used when requesting an ID token from an identity provider for auth keys generated by workload identity federation.
        """
        return pulumi.get(self, "audience")

    @audience.setter
    def audience(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "audience", value)

    @_builtins.property
    @pulumi.getter
    def auth_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Node authorization key; if it begins with 'file:', then it's a path to a file containing the authkey; if it begins with 'command:', then it's a command to execute that outputs the authkey
        """
        return pulumi.get(self, "auth_key")

    @auth_key.setter
    def auth_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "auth_key", value)

    @_builtins.property
    @pulumi.getter
    def base64_encode(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether to base64 encode the cloud-init data
        """
        return pulumi.get(self, "base64_encode")

    @base64_encode.setter
    def base64_encode(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "base64_encode", value)

    @_builtins.property
    @pulumi.getter
    def client_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Client ID used to generate authkeys via workload identity federation
        """
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "client_id", value)

    @_builtins.property
    @pulumi.getter
    def client_secret(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Client Secret used to generate authkeys via OAuth; if it begins with "file:", then it's a path to a file containing the secret; if it begins with "command:", then it's a command to execute that outputs the secret
        """
        return pulumi.get(self, "client_secret")

    @client_secret.setter
    def client_secret(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "client_secret", value)

    @_builtins.property
    @pulumi.getter
    def enable_ssh(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Enable SSH access via Tailscale
        """
        return pulumi.get(self, "enable_ssh")

    @enable_ssh.setter
    def enable_ssh(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enable_ssh", value)

    @_builtins.property
    @pulumi.getter
    def exit_node(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Tailscale exit node (IP or base name) for internet traffic
        """
        return pulumi.get(self, "exit_node")

    @exit_node.setter
    def exit_node(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "exit_node", value)

    @_builtins.property
    @pulumi.getter
    def exit_node_allow_lan_access(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Allow direct access to the local network when routing traffic via an exit node
        """
        return pulumi.get(self, "exit_node_allow_lan_access")

    @exit_node_allow_lan_access.setter
    def exit_node_allow_lan_access(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "exit_node_allow_lan_access", value)

    @_builtins.property
    @pulumi.getter
    def force_reauth(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        force reauthentication
        """
        return pulumi.get(self, "force_reauth")

    @force_reauth.setter
    def force_reauth(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "force_reauth", value)

    @_builtins.property
    @pulumi.getter
    def gzip(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether to gzip the cloud-init data
        """
        return pulumi.get(self, "gzip")

    @gzip.setter
    def gzip(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "gzip", value)

    @_builtins.property
    @pulumi.getter
    def hostname(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Hostname of the instance
        """
        return pulumi.get(self, "hostname")

    @hostname.setter
    def hostname(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "hostname", value)

    @_builtins.property
    @pulumi.getter
    def id_token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID token from the identity provider to exchange with the control server for workload identity federation; if it begins with "file:", then it's a path to a file containing the token; if it begins with "command:", then it's a command to execute that outputs the token
        """
        return pulumi.get(self, "id_token")

    @id_token.setter
    def id_token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "id_token", value)

    @_builtins.property
    @pulumi.getter
    def json(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        output in JSON format
        """
        return pulumi.get(self, "json")

    @json.setter
    def json(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "json", value)

    @_builtins.property
    @pulumi.getter
    def login_server(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        base URL of control server
        """
        return pulumi.get(self, "login_server")

    @login_server.setter
    def login_server(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "login_server", value)

    @_builtins.property
    @pulumi.getter
    def max_retries(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        maximum number of retries to connect to the control server
        """
        return pulumi.get(self, "max_retries")

    @max_retries.setter
    def max_retries(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "max_retries", value)

    @_builtins.property
    @pulumi.getter
    def netfilter_mode(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        netfilter mode
        """
        return pulumi.get(self, "netfilter_mode")

    @netfilter_mode.setter
    def netfilter_mode(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "netfilter_mode", value)

    @_builtins.property
    @pulumi.getter
    def operator(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Unix username to allow to operate on tailscaled without sudo
        """
        return pulumi.get(self, "operator")

    @operator.setter
    def operator(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "operator", value)

    @_builtins.property
    @pulumi.getter
    def relay_server_port(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Port for the Tailscale relay server; when null, peer relay advertisement is not configured
        """
        return pulumi.get(self, "relay_server_port")

    @relay_server_port.setter
    def relay_server_port(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "relay_server_port", value)

    @_builtins.property
    @pulumi.getter
    def reset(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        reset unspecified settings to their default values
        """
        return pulumi.get(self, "reset")

    @reset.setter
    def reset(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "reset", value)

    @_builtins.property
    @pulumi.getter
    def retry_delay(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        delay in seconds between retries to connect to the control server
        """
        return pulumi.get(self, "retry_delay")

    @retry_delay.setter
    def retry_delay(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "retry_delay", value)

    @_builtins.property
    @pulumi.getter
    def shields_up(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        don't allow incoming connections
        """
        return pulumi.get(self, "shields_up")

    @shields_up.setter
    def shields_up(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "shields_up", value)

    @_builtins.property
    @pulumi.getter
    def snat_subnet_routes(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        source NAT traffic to local routes advertised with --advertise-routes
        """
        return pulumi.get(self, "snat_subnet_routes")

    @snat_subnet_routes.setter
    def snat_subnet_routes(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "snat_subnet_routes", value)

    @_builtins.property
    @pulumi.getter
    def stateful_filtering(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        apply stateful filtering to forwarded packets
        """
        return pulumi.get(self, "stateful_filtering")

    @stateful_filtering.setter
    def stateful_filtering(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "stateful_filtering", value)

    @_builtins.property
    @pulumi.getter
    def tailscaled_flag_bird_socket(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        path of the bird unix socket
        """
        return pulumi.get(self, "tailscaled_flag_bird_socket")

    @tailscaled_flag_bird_socket.setter
    def tailscaled_flag_bird_socket(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tailscaled_flag_bird_socket", value)

    @_builtins.property
    @pulumi.getter
    def tailscaled_flag_config(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        path to config file, or 'vm:user-data' to use the VM's user-data (EC2)
        """
        return pulumi.get(self, "tailscaled_flag_config")

    @tailscaled_flag_config.setter
    def tailscaled_flag_config(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tailscaled_flag_config", value)

    @_builtins.property
    @pulumi.getter
    def tailscaled_flag_debug(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        listen address ([ip]:port) of optional debug server
        """
        return pulumi.get(self, "tailscaled_flag_debug")

    @tailscaled_flag_debug.setter
    def tailscaled_flag_debug(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tailscaled_flag_debug", value)

    @_builtins.property
    @pulumi.getter
    def tailscaled_flag_encrypt_state(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        encrypt the state file on disk; uses TPM on Linux and Windows
        """
        return pulumi.get(self, "tailscaled_flag_encrypt_state")

    @tailscaled_flag_encrypt_state.setter
    def tailscaled_flag_encrypt_state(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "tailscaled_flag_encrypt_state", value)

    @_builtins.property
    @pulumi.getter
    def tailscaled_flag_no_logs_no_support(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        disable log uploads; this also disables any technical support
        """
        return pulumi.get(self, "tailscaled_flag_no_logs_no_support")

    @tailscaled_flag_no_logs_no_support.setter
    def tailscaled_flag_no_logs_no_support(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "tailscaled_flag_no_logs_no_support", value)

    @_builtins.property
    @pulumi.getter
    def tailscaled_flag_outbound_http_proxy_listen(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        optional [ip]:port to run an outbound HTTP proxy (e.g. "localhost:8080")
        """
        return pulumi.get(self, "tailscaled_flag_outbound_http_proxy_listen")

    @tailscaled_flag_outbound_http_proxy_listen.setter
    def tailscaled_flag_outbound_http_proxy_listen(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tailscaled_flag_outbound_http_proxy_listen", value)

    @_builtins.property
    @pulumi.getter
    def tailscaled_flag_port(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        UDP port to listen on for WireGuard and peer-to-peer traffic; 0 means automatically select
        """
        return pulumi.get(self, "tailscaled_flag_port")

    @tailscaled_flag_port.setter
    def tailscaled_flag_port(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "tailscaled_flag_port", value)

    @_builtins.property
    @pulumi.getter
    def tailscaled_flag_socket(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        path of the service unix socket
        """
        return pulumi.get(self, "tailscaled_flag_socket")

    @tailscaled_flag_socket.setter
    def tailscaled_flag_socket(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tailscaled_flag_socket", value)

    @_builtins.property
    @pulumi.getter
    def tailscaled_flag_socks5_server(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        optional [ip]:port to run a SOCK5 server (e.g. "localhost:1080")
        """
        return pulumi.get(self, "tailscaled_flag_socks5_server")

    @tailscaled_flag_socks5_server.setter
    def tailscaled_flag_socks5_server(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tailscaled_flag_socks5_server", value)

    @_builtins.property
    @pulumi.getter
    def tailscaled_flag_state(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        absolute path of state file; use 'kube:<secret-name>' to use Kubernetes secrets or 'arn:aws:ssm:...' to store in AWS SSM; use 'mem:' to not store state and register as an ephemeral node
        """
        return pulumi.get(self, "tailscaled_flag_state")

    @tailscaled_flag_state.setter
    def tailscaled_flag_state(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tailscaled_flag_state", value)

    @_builtins.property
    @pulumi.getter
    def tailscaled_flag_statedir(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        path to directory for storage of config state, TLS certs, temporary incoming Taildrop files, etc.
        """
        return pulumi.get(self, "tailscaled_flag_statedir")

    @tailscaled_flag_statedir.setter
    def tailscaled_flag_statedir(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tailscaled_flag_statedir", value)

    @_builtins.property
    @pulumi.getter
    def tailscaled_flag_tun(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        tunnel interface name; use "userspace-networking" (beta) to not use TUN
        """
        return pulumi.get(self, "tailscaled_flag_tun")

    @tailscaled_flag_tun.setter
    def tailscaled_flag_tun(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tailscaled_flag_tun", value)

    @_builtins.property
    @pulumi.getter
    def tailscaled_flag_verbose(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        log verbosity level; 0 is default, 1 or higher are increasingly verbose
        """
        return pulumi.get(self, "tailscaled_flag_verbose")

    @tailscaled_flag_verbose.setter
    def tailscaled_flag_verbose(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "tailscaled_flag_verbose", value)

    @_builtins.property
    @pulumi.getter
    def timeout(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        maximum amount of time to wait for tailscaled to enter a Running state
        """
        return pulumi.get(self, "timeout")

    @timeout.setter
    def timeout(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "timeout", value)

    @_builtins.property
    @pulumi.getter
    def track(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Version of the Tailscale client to install
        """
        return pulumi.get(self, "track")

    @track.setter
    def track(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "track", value)


@pulumi.type_token("cloudinit-tailscale:index:Module")
class Module(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 accept_dns: Optional[pulumi.Input[_builtins.bool]] = None,
                 accept_routes: Optional[pulumi.Input[_builtins.bool]] = None,
                 additional_parts: Optional[pulumi.Input[Sequence[pulumi.Input[Union['AdditionalPartsArgs', 'AdditionalPartsArgsDict']]]]] = None,
                 advertise_connector: Optional[pulumi.Input[_builtins.bool]] = None,
                 advertise_exit_node: Optional[pulumi.Input[_builtins.bool]] = None,
                 advertise_routes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 advertise_tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 audience: Optional[pulumi.Input[_builtins.str]] = None,
                 auth_key: Optional[pulumi.Input[_builtins.str]] = None,
                 base64_encode: Optional[pulumi.Input[_builtins.bool]] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_ssh: Optional[pulumi.Input[_builtins.bool]] = None,
                 exit_node: Optional[pulumi.Input[_builtins.str]] = None,
                 exit_node_allow_lan_access: Optional[pulumi.Input[_builtins.bool]] = None,
                 force_reauth: Optional[pulumi.Input[_builtins.bool]] = None,
                 gzip: Optional[pulumi.Input[_builtins.bool]] = None,
                 hostname: Optional[pulumi.Input[_builtins.str]] = None,
                 id_token: Optional[pulumi.Input[_builtins.str]] = None,
                 json: Optional[pulumi.Input[_builtins.bool]] = None,
                 login_server: Optional[pulumi.Input[_builtins.str]] = None,
                 max_retries: Optional[pulumi.Input[_builtins.float]] = None,
                 netfilter_mode: Optional[pulumi.Input[_builtins.str]] = None,
                 operator: Optional[pulumi.Input[_builtins.str]] = None,
                 relay_server_port: Optional[pulumi.Input[_builtins.float]] = None,
                 reset: Optional[pulumi.Input[_builtins.bool]] = None,
                 retry_delay: Optional[pulumi.Input[_builtins.float]] = None,
                 shields_up: Optional[pulumi.Input[_builtins.bool]] = None,
                 snat_subnet_routes: Optional[pulumi.Input[_builtins.bool]] = None,
                 stateful_filtering: Optional[pulumi.Input[_builtins.bool]] = None,
                 tailscaled_flag_bird_socket: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_config: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_debug: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_encrypt_state: Optional[pulumi.Input[_builtins.bool]] = None,
                 tailscaled_flag_no_logs_no_support: Optional[pulumi.Input[_builtins.bool]] = None,
                 tailscaled_flag_outbound_http_proxy_listen: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_port: Optional[pulumi.Input[_builtins.float]] = None,
                 tailscaled_flag_socket: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_socks5_server: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_state: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_statedir: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_tun: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_verbose: Optional[pulumi.Input[_builtins.float]] = None,
                 timeout: Optional[pulumi.Input[_builtins.str]] = None,
                 track: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Module resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] accept_dns: Accept DNS configuration from Tailscale
        :param pulumi.Input[_builtins.bool] accept_routes: Accept routes from Tailscale
        :param pulumi.Input[Sequence[pulumi.Input[Union['AdditionalPartsArgs', 'AdditionalPartsArgsDict']]]] additional_parts: Additional user defined part blocks for the cloudinit_config data source
        :param pulumi.Input[_builtins.bool] advertise_connector: Advertise this node as an app connector
        :param pulumi.Input[_builtins.bool] advertise_exit_node: Offer to be an exit node for internet traffic for the tailnet
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] advertise_routes: Routes to advertise to other nodes
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] advertise_tags: ACL tags to request; each must start with 'tag:' (e.g. 'tag:eng,tag:montreal,tag:ssh')
        :param pulumi.Input[_builtins.str] audience: Audience used when requesting an ID token from an identity provider for auth keys generated by workload identity federation.
        :param pulumi.Input[_builtins.str] auth_key: Node authorization key; if it begins with 'file:', then it's a path to a file containing the authkey; if it begins with 'command:', then it's a command to execute that outputs the authkey
        :param pulumi.Input[_builtins.bool] base64_encode: Whether to base64 encode the cloud-init data
        :param pulumi.Input[_builtins.str] client_id: Client ID used to generate authkeys via workload identity federation
        :param pulumi.Input[_builtins.str] client_secret: Client Secret used to generate authkeys via OAuth; if it begins with "file:", then it's a path to a file containing the secret; if it begins with "command:", then it's a command to execute that outputs the secret
        :param pulumi.Input[_builtins.bool] enable_ssh: Enable SSH access via Tailscale
        :param pulumi.Input[_builtins.str] exit_node: Tailscale exit node (IP or base name) for internet traffic
        :param pulumi.Input[_builtins.bool] exit_node_allow_lan_access: Allow direct access to the local network when routing traffic via an exit node
        :param pulumi.Input[_builtins.bool] force_reauth: force reauthentication
        :param pulumi.Input[_builtins.bool] gzip: Whether to gzip the cloud-init data
        :param pulumi.Input[_builtins.str] hostname: Hostname of the instance
        :param pulumi.Input[_builtins.str] id_token: ID token from the identity provider to exchange with the control server for workload identity federation; if it begins with "file:", then it's a path to a file containing the token; if it begins with "command:", then it's a command to execute that outputs the token
        :param pulumi.Input[_builtins.bool] json: output in JSON format
        :param pulumi.Input[_builtins.str] login_server: base URL of control server
        :param pulumi.Input[_builtins.float] max_retries: maximum number of retries to connect to the control server
        :param pulumi.Input[_builtins.str] netfilter_mode: netfilter mode
        :param pulumi.Input[_builtins.str] operator: Unix username to allow to operate on tailscaled without sudo
        :param pulumi.Input[_builtins.float] relay_server_port: Port for the Tailscale relay server; when null, peer relay advertisement is not configured
        :param pulumi.Input[_builtins.bool] reset: reset unspecified settings to their default values
        :param pulumi.Input[_builtins.float] retry_delay: delay in seconds between retries to connect to the control server
        :param pulumi.Input[_builtins.bool] shields_up: don't allow incoming connections
        :param pulumi.Input[_builtins.bool] snat_subnet_routes: source NAT traffic to local routes advertised with --advertise-routes
        :param pulumi.Input[_builtins.bool] stateful_filtering: apply stateful filtering to forwarded packets
        :param pulumi.Input[_builtins.str] tailscaled_flag_bird_socket: path of the bird unix socket
        :param pulumi.Input[_builtins.str] tailscaled_flag_config: path to config file, or 'vm:user-data' to use the VM's user-data (EC2)
        :param pulumi.Input[_builtins.str] tailscaled_flag_debug: listen address ([ip]:port) of optional debug server
        :param pulumi.Input[_builtins.bool] tailscaled_flag_encrypt_state: encrypt the state file on disk; uses TPM on Linux and Windows
        :param pulumi.Input[_builtins.bool] tailscaled_flag_no_logs_no_support: disable log uploads; this also disables any technical support
        :param pulumi.Input[_builtins.str] tailscaled_flag_outbound_http_proxy_listen: optional [ip]:port to run an outbound HTTP proxy (e.g. "localhost:8080")
        :param pulumi.Input[_builtins.float] tailscaled_flag_port: UDP port to listen on for WireGuard and peer-to-peer traffic; 0 means automatically select
        :param pulumi.Input[_builtins.str] tailscaled_flag_socket: path of the service unix socket
        :param pulumi.Input[_builtins.str] tailscaled_flag_socks5_server: optional [ip]:port to run a SOCK5 server (e.g. "localhost:1080")
        :param pulumi.Input[_builtins.str] tailscaled_flag_state: absolute path of state file; use 'kube:<secret-name>' to use Kubernetes secrets or 'arn:aws:ssm:...' to store in AWS SSM; use 'mem:' to not store state and register as an ephemeral node
        :param pulumi.Input[_builtins.str] tailscaled_flag_statedir: path to directory for storage of config state, TLS certs, temporary incoming Taildrop files, etc.
        :param pulumi.Input[_builtins.str] tailscaled_flag_tun: tunnel interface name; use "userspace-networking" (beta) to not use TUN
        :param pulumi.Input[_builtins.float] tailscaled_flag_verbose: log verbosity level; 0 is default, 1 or higher are increasingly verbose
        :param pulumi.Input[_builtins.str] timeout: maximum amount of time to wait for tailscaled to enter a Running state
        :param pulumi.Input[_builtins.str] track: Version of the Tailscale client to install
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ModuleArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Module resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ModuleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ModuleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 accept_dns: Optional[pulumi.Input[_builtins.bool]] = None,
                 accept_routes: Optional[pulumi.Input[_builtins.bool]] = None,
                 additional_parts: Optional[pulumi.Input[Sequence[pulumi.Input[Union['AdditionalPartsArgs', 'AdditionalPartsArgsDict']]]]] = None,
                 advertise_connector: Optional[pulumi.Input[_builtins.bool]] = None,
                 advertise_exit_node: Optional[pulumi.Input[_builtins.bool]] = None,
                 advertise_routes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 advertise_tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 audience: Optional[pulumi.Input[_builtins.str]] = None,
                 auth_key: Optional[pulumi.Input[_builtins.str]] = None,
                 base64_encode: Optional[pulumi.Input[_builtins.bool]] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 client_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_ssh: Optional[pulumi.Input[_builtins.bool]] = None,
                 exit_node: Optional[pulumi.Input[_builtins.str]] = None,
                 exit_node_allow_lan_access: Optional[pulumi.Input[_builtins.bool]] = None,
                 force_reauth: Optional[pulumi.Input[_builtins.bool]] = None,
                 gzip: Optional[pulumi.Input[_builtins.bool]] = None,
                 hostname: Optional[pulumi.Input[_builtins.str]] = None,
                 id_token: Optional[pulumi.Input[_builtins.str]] = None,
                 json: Optional[pulumi.Input[_builtins.bool]] = None,
                 login_server: Optional[pulumi.Input[_builtins.str]] = None,
                 max_retries: Optional[pulumi.Input[_builtins.float]] = None,
                 netfilter_mode: Optional[pulumi.Input[_builtins.str]] = None,
                 operator: Optional[pulumi.Input[_builtins.str]] = None,
                 relay_server_port: Optional[pulumi.Input[_builtins.float]] = None,
                 reset: Optional[pulumi.Input[_builtins.bool]] = None,
                 retry_delay: Optional[pulumi.Input[_builtins.float]] = None,
                 shields_up: Optional[pulumi.Input[_builtins.bool]] = None,
                 snat_subnet_routes: Optional[pulumi.Input[_builtins.bool]] = None,
                 stateful_filtering: Optional[pulumi.Input[_builtins.bool]] = None,
                 tailscaled_flag_bird_socket: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_config: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_debug: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_encrypt_state: Optional[pulumi.Input[_builtins.bool]] = None,
                 tailscaled_flag_no_logs_no_support: Optional[pulumi.Input[_builtins.bool]] = None,
                 tailscaled_flag_outbound_http_proxy_listen: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_port: Optional[pulumi.Input[_builtins.float]] = None,
                 tailscaled_flag_socket: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_socks5_server: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_state: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_statedir: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_tun: Optional[pulumi.Input[_builtins.str]] = None,
                 tailscaled_flag_verbose: Optional[pulumi.Input[_builtins.float]] = None,
                 timeout: Optional[pulumi.Input[_builtins.str]] = None,
                 track: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ModuleArgs.__new__(ModuleArgs)

            __props__.__dict__["accept_dns"] = accept_dns
            __props__.__dict__["accept_routes"] = accept_routes
            __props__.__dict__["additional_parts"] = additional_parts
            __props__.__dict__["advertise_connector"] = advertise_connector
            __props__.__dict__["advertise_exit_node"] = advertise_exit_node
            __props__.__dict__["advertise_routes"] = advertise_routes
            __props__.__dict__["advertise_tags"] = advertise_tags
            __props__.__dict__["audience"] = audience
            __props__.__dict__["auth_key"] = None if auth_key is None else pulumi.Output.secret(auth_key)
            __props__.__dict__["base64_encode"] = base64_encode
            __props__.__dict__["client_id"] = client_id
            __props__.__dict__["client_secret"] = None if client_secret is None else pulumi.Output.secret(client_secret)
            __props__.__dict__["enable_ssh"] = enable_ssh
            __props__.__dict__["exit_node"] = exit_node
            __props__.__dict__["exit_node_allow_lan_access"] = exit_node_allow_lan_access
            __props__.__dict__["force_reauth"] = force_reauth
            __props__.__dict__["gzip"] = gzip
            __props__.__dict__["hostname"] = hostname
            __props__.__dict__["id_token"] = None if id_token is None else pulumi.Output.secret(id_token)
            __props__.__dict__["json"] = json
            __props__.__dict__["login_server"] = login_server
            __props__.__dict__["max_retries"] = max_retries
            __props__.__dict__["netfilter_mode"] = netfilter_mode
            __props__.__dict__["operator"] = operator
            __props__.__dict__["relay_server_port"] = relay_server_port
            __props__.__dict__["reset"] = reset
            __props__.__dict__["retry_delay"] = retry_delay
            __props__.__dict__["shields_up"] = shields_up
            __props__.__dict__["snat_subnet_routes"] = snat_subnet_routes
            __props__.__dict__["stateful_filtering"] = stateful_filtering
            __props__.__dict__["tailscaled_flag_bird_socket"] = tailscaled_flag_bird_socket
            __props__.__dict__["tailscaled_flag_config"] = tailscaled_flag_config
            __props__.__dict__["tailscaled_flag_debug"] = tailscaled_flag_debug
            __props__.__dict__["tailscaled_flag_encrypt_state"] = tailscaled_flag_encrypt_state
            __props__.__dict__["tailscaled_flag_no_logs_no_support"] = tailscaled_flag_no_logs_no_support
            __props__.__dict__["tailscaled_flag_outbound_http_proxy_listen"] = tailscaled_flag_outbound_http_proxy_listen
            __props__.__dict__["tailscaled_flag_port"] = tailscaled_flag_port
            __props__.__dict__["tailscaled_flag_socket"] = tailscaled_flag_socket
            __props__.__dict__["tailscaled_flag_socks5_server"] = tailscaled_flag_socks5_server
            __props__.__dict__["tailscaled_flag_state"] = tailscaled_flag_state
            __props__.__dict__["tailscaled_flag_statedir"] = tailscaled_flag_statedir
            __props__.__dict__["tailscaled_flag_tun"] = tailscaled_flag_tun
            __props__.__dict__["tailscaled_flag_verbose"] = tailscaled_flag_verbose
            __props__.__dict__["timeout"] = timeout
            __props__.__dict__["track"] = track
            __props__.__dict__["rendered"] = None
        super(Module, __self__).__init__(
            'cloudinit-tailscale:index:Module',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Module':
        """
        Get an existing Module resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ModuleArgs.__new__(ModuleArgs)

        __props__.__dict__["rendered"] = None
        return Module(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def rendered(self) -> pulumi.Output[Optional[Any]]:
        return pulumi.get(self, "rendered")

